### ISSUE TITLE
Wrong unused dep detected

### ISSUE THREAD

**Issue by heruan** [depcheck/depcheck#189]
I have this TypeScript code:

```typescript
import { FrameworkConfiguration } from "aurelia-framework";
import { Container } from "aurelia-dependency-injection";

export function configure(frameworkConfiguration: FrameworkConfiguration, pluginConfiguration: Function) {
    let container: Container = frameworkConfiguration.container;
    // other code
}
```
and packages `aurelia-dependency-injection` and `aurelia-framework` installed:
```json
{
  "//": "other package.json entries",
  "dependencies": {
    "aurelia-dependency-injection": "^1.2.0",
    "aurelia-framework": "^1.0.7",
    "aurelia-http-client": "^1.0.3",
    "aurelia-http-utils": "^0.2.2",
    "type-binder": "^0.2.0"
  }
}
```

But…
```
$ depcheck
Unused dependencies
* aurelia-framework
```

**Comment by heruan** [comment]
I suspect that types imported and used in function arguments are not considered by `depcheck`.

**Comment by lijunle** [comment]
It looks strange that, `aurelia-framework` is reported as *unused*. What is the output with `--json` parameter?

**Comment by heruan** [comment]
```json
{
  "dependencies": [
    "aurelia-framework"
  ],
  "devDependencies": [
    "babel-register",
    "jasmine"
  ],
  "missing": {},
  "using": {
    "babel-preset-es2015": [
      "/Users/lovatog/Workspaces/aurelia/packages/aurelia-json/.babelrc"
    ],
    "aurelia-http-client": [
      "/Users/lovatog/Workspaces/aurelia/packages/aurelia-json/dist/main/index.js",
      "/Users/lovatog/Workspaces/aurelia/packages/aurelia-json/src/main/index.ts"
    ],
    "aurelia-dependency-injection": [
      "/Users/lovatog/Workspaces/aurelia/packages/aurelia-json/dist/main/json-decoder.js",
      "/Users/lovatog/Workspaces/aurelia/packages/aurelia-json/src/main/json-decoder.ts"
    ],
    "type-binder": [
      "/Users/lovatog/Workspaces/aurelia/packages/aurelia-json/dist/main/json-decoder.js",
      "/Users/lovatog/Workspaces/aurelia/packages/aurelia-json/dist/main/json-patch.js",
      "/Users/lovatog/Workspaces/aurelia/packages/aurelia-json/dist/test/unit/json-encoder.js",
      "/Users/lovatog/Workspaces/aurelia/packages/aurelia-json/dist/test/unit/json-patch.js",
      "/Users/lovatog/Workspaces/aurelia/packages/aurelia-json/src/main/json-decoder.ts",
      "/Users/lovatog/Workspaces/aurelia/packages/aurelia-json/src/main/json-patch.ts",
      "/Users/lovatog/Workspaces/aurelia/packages/aurelia-json/src/test/unit/json-patch.ts",
      "/Users/lovatog/Workspaces/aurelia/packages/aurelia-json/src/test/unit/json-encoder.ts"
    ],
    "aurelia-http-utils": [
      "/Users/lovatog/Workspaces/aurelia/packages/aurelia-json/dist/main/json-multipart-related-interceptor.js",
      "/Users/lovatog/Workspaces/aurelia/packages/aurelia-json/src/main/json-multipart-related-interceptor.ts"
    ],
    "gulp": [
      "/Users/lovatog/Workspaces/aurelia/packages/aurelia-json/gulpfile.babel.js",
      "/Users/lovatog/Workspaces/aurelia/packages/aurelia-json/package.json"
    ],
    "vinyl-paths": [
      "/Users/lovatog/Workspaces/aurelia/packages/aurelia-json/gulpfile.babel.js"
    ],
    "del": [
      "/Users/lovatog/Workspaces/aurelia/packages/aurelia-json/gulpfile.babel.js"
    ],
    "run-sequence": [
      "/Users/lovatog/Workspaces/aurelia/packages/aurelia-json/gulpfile.babel.js"
    ],
    "gulp-jasmine": [
      "/Users/lovatog/Workspaces/aurelia/packages/aurelia-json/gulpfile.babel.js"
    ],
    "jasmine-reporters": [
      "/Users/lovatog/Workspaces/aurelia/packages/aurelia-json/gulpfile.babel.js"
    ],
    "typescript": [
      "/Users/lovatog/Workspaces/aurelia/packages/aurelia-json/gulpfile.babel.js"
    ],
    "gulp-typings": [
      "/Users/lovatog/Workspaces/aurelia/packages/aurelia-json/gulpfile.babel.js"
    ],
    "gulp-typescript": [
      "/Users/lovatog/Workspaces/aurelia/packages/aurelia-json/gulpfile.babel.js"
    ],
    "gulp-sass": [
      "/Users/lovatog/Workspaces/aurelia/packages/aurelia-json/gulpfile.babel.js"
    ],
    "merge2": [
      "/Users/lovatog/Workspaces/aurelia/packages/aurelia-json/gulpfile.babel.js"
    ]
  },
  "invalidFiles": {
    "/Users/lovatog/Workspaces/aurelia/packages/aurelia-json/dist/main/decorators.d.ts": "Error: Debug Failure. False expression: Output generation failed\n    at Object.assert (/usr/local/lib/node_modules/typescript/lib/typescript.js:3001:23)\n    at transpileModule (/usr/local/lib/node_modules/typescript/lib/typescript.js:71114:18)\n    at Object.transpile (/usr/local/lib/node_modules/typescript/lib/typescript.js:71122:22)\n    at parseTypescript (/usr/local/lib/node_modules/depcheck/dist/parser/typescript.js:24:27)\n    at /usr/local/lib/node_modules/depcheck/dist/check.js:129:17\n    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)",
    "/Users/lovatog/Workspaces/aurelia/packages/aurelia-json/dist/main/index.d.ts": "Error: Debug Failure. False expression: Output generation failed\n    at Object.assert (/usr/local/lib/node_modules/typescript/lib/typescript.js:3001:23)\n    at transpileModule (/usr/local/lib/node_modules/typescript/lib/typescript.js:71114:18)\n    at Object.transpile (/usr/local/lib/node_modules/typescript/lib/typescript.js:71122:22)\n    at parseTypescript (/usr/local/lib/node_modules/depcheck/dist/parser/typescript.js:24:27)\n    at /usr/local/lib/node_modules/depcheck/dist/check.js:129:17\n    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)",
    "/Users/lovatog/Workspaces/aurelia/packages/aurelia-json/dist/main/json-decoder.d.ts": "Error: Debug Failure. False expression: Output generation failed\n    at Object.assert (/usr/local/lib/node_modules/typescript/lib/typescript.js:3001:23)\n    at transpileModule (/usr/local/lib/node_modules/typescript/lib/typescript.js:71114:18)\n    at Object.transpile (/usr/local/lib/node_modules/typescript/lib/typescript.js:71122:22)\n    at parseTypescript (/usr/local/lib/node_modules/depcheck/dist/parser/typescript.js:24:27)\n    at /usr/local/lib/node_modules/depcheck/dist/check.js:129:17\n    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)",
    "/Users/lovatog/Workspaces/aurelia/packages/aurelia-json/dist/main/json-multipart-related-interceptor.d.ts": "Error: Debug Failure. False expression: Output generation failed\n    at Object.assert (/usr/local/lib/node_modules/typescript/lib/typescript.js:3001:23)\n    at transpileModule (/usr/local/lib/node_modules/typescript/lib/typescript.js:71114:18)\n    at Object.transpile (/usr/local/lib/node_modules/typescript/lib/typescript.js:71122:22)\n    at parseTypescript (/usr/local/lib/node_modules/depcheck/dist/parser/typescript.js:24:27)\n    at /usr/local/lib/node_modules/depcheck/dist/check.js:129:17\n    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)",
    "/Users/lovatog/Workspaces/aurelia/packages/aurelia-json/dist/main/json-encoder.d.ts": "Error: Debug Failure. False expression: Output generation failed\n    at Object.assert (/usr/local/lib/node_modules/typescript/lib/typescript.js:3001:23)\n    at transpileModule (/usr/local/lib/node_modules/typescript/lib/typescript.js:71114:18)\n    at Object.transpile (/usr/local/lib/node_modules/typescript/lib/typescript.js:71122:22)\n    at parseTypescript (/usr/local/lib/node_modules/depcheck/dist/parser/typescript.js:24:27)\n    at /usr/local/lib/node_modules/depcheck/dist/check.js:129:17\n    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)",
    "/Users/lovatog/Workspaces/aurelia/packages/aurelia-json/dist/main/json-patch.d.ts": "Error: Debug Failure. False expression: Output generation failed\n    at Object.assert (/usr/local/lib/node_modules/typescript/lib/typescript.js:3001:23)\n    at transpileModule (/usr/local/lib/node_modules/typescript/lib/typescript.js:71114:18)\n    at Object.transpile (/usr/local/lib/node_modules/typescript/lib/typescript.js:71122:22)\n    at parseTypescript (/usr/local/lib/node_modules/depcheck/dist/parser/typescript.js:24:27)\n    at /usr/local/lib/node_modules/depcheck/dist/check.js:129:17\n    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)",
    "/Users/lovatog/Workspaces/aurelia/packages/aurelia-json/dist/main/json-pointer.d.ts": "Error: Debug Failure. False expression: Output generation failed\n    at Object.assert (/usr/local/lib/node_modules/typescript/lib/typescript.js:3001:23)\n    at transpileModule (/usr/local/lib/node_modules/typescript/lib/typescript.js:71114:18)\n    at Object.transpile (/usr/local/lib/node_modules/typescript/lib/typescript.js:71122:22)\n    at parseTypescript (/usr/local/lib/node_modules/depcheck/dist/parser/typescript.js:24:27)\n    at /usr/local/lib/node_modules/depcheck/dist/check.js:129:17\n    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)",
    "/Users/lovatog/Workspaces/aurelia/packages/aurelia-json/dist/main/json-schema.d.ts": "Error: Debug Failure. False expression: Output generation failed\n    at Object.assert (/usr/local/lib/node_modules/typescript/lib/typescript.js:3001:23)\n    at transpileModule (/usr/local/lib/node_modules/typescript/lib/typescript.js:71114:18)\n    at Object.transpile (/usr/local/lib/node_modules/typescript/lib/typescript.js:71122:22)\n    at parseTypescript (/usr/local/lib/node_modules/depcheck/dist/parser/typescript.js:24:27)\n    at /usr/local/lib/node_modules/depcheck/dist/check.js:129:17\n    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)",
    "/Users/lovatog/Workspaces/aurelia/packages/aurelia-json/dist/main/metadata-keys.d.ts": "Error: Debug Failure. False expression: Output generation failed\n    at Object.assert (/usr/local/lib/node_modules/typescript/lib/typescript.js:3001:23)\n    at transpileModule (/usr/local/lib/node_modules/typescript/lib/typescript.js:71114:18)\n    at Object.transpile (/usr/local/lib/node_modules/typescript/lib/typescript.js:71122:22)\n    at parseTypescript (/usr/local/lib/node_modules/depcheck/dist/parser/typescript.js:24:27)\n    at /usr/local/lib/node_modules/depcheck/dist/check.js:129:17\n    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)",
    "/Users/lovatog/Workspaces/aurelia/packages/aurelia-json/dist/test/unit/json-encoder.d.ts": "Error: Debug Failure. False expression: Output generation failed\n    at Object.assert (/usr/local/lib/node_modules/typescript/lib/typescript.js:3001:23)\n    at transpileModule (/usr/local/lib/node_modules/typescript/lib/typescript.js:71114:18)\n    at Object.transpile (/usr/local/lib/node_modules/typescript/lib/typescript.js:71122:22)\n    at parseTypescript (/usr/local/lib/node_modules/depcheck/dist/parser/typescript.js:24:27)\n    at /usr/local/lib/node_modules/depcheck/dist/check.js:129:17\n    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)",
    "/Users/lovatog/Workspaces/aurelia/packages/aurelia-json/dist/test/unit/json-patch.d.ts": "Error: Debug Failure. False expression: Output generation failed\n    at Object.assert (/usr/local/lib/node_modules/typescript/lib/typescript.js:3001:23)\n    at transpileModule (/usr/local/lib/node_modules/typescript/lib/typescript.js:71114:18)\n    at Object.transpile (/usr/local/lib/node_modules/typescript/lib/typescript.js:71122:22)\n    at parseTypescript (/usr/local/lib/node_modules/depcheck/dist/parser/typescript.js:24:27)\n    at /usr/local/lib/node_modules/depcheck/dist/check.js:129:17\n    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)",
    "/Users/lovatog/Workspaces/aurelia/packages/aurelia-json/src/typings/globals/jasmine/index.d.ts": "Error: Debug Failure. False expression: Output generation failed\n    at Object.assert (/usr/local/lib/node_modules/typescript/lib/typescript.js:3001:23)\n    at transpileModule (/usr/local/lib/node_modules/typescript/lib/typescript.js:71114:18)\n    at Object.transpile (/usr/local/lib/node_modules/typescript/lib/typescript.js:71122:22)\n    at parseTypescript (/usr/local/lib/node_modules/depcheck/dist/parser/typescript.js:24:27)\n    at /usr/local/lib/node_modules/depcheck/dist/check.js:129:17\n    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)",
    "/Users/lovatog/Workspaces/aurelia/packages/aurelia-json/src/typings/index.d.ts": "Error: Debug Failure. False expression: Output generation failed\n    at Object.assert (/usr/local/lib/node_modules/typescript/lib/typescript.js:3001:23)\n    at transpileModule (/usr/local/lib/node_modules/typescript/lib/typescript.js:71114:18)\n    at Object.transpile (/usr/local/lib/node_modules/typescript/lib/typescript.js:71122:22)\n    at parseTypescript (/usr/local/lib/node_modules/depcheck/dist/parser/typescript.js:24:27)\n    at /usr/local/lib/node_modules/depcheck/dist/check.js:129:17\n    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)"
  },
  "invalidDirs": {}
}
```

**Comment by anuragl94** [comment]
I'm facing a similar issue. Folder structure is something like this:
```
/root-folder
  -/package.json
  -/node_modules
  -/sub-app1
    -/index.js
  -/sub-app2
    -/index.js
```

Almost all dependencies are listed as unused.

**Comment by ckknight** [comment]
Yeah, if they are only types imported, then `depcheck` appears to discard it, which is less-than-ideal.

**Comment by XBeg9** [comment]
Facing same issue here, any ideas how to fix that?

**Comment by rumpl** [comment]
Hey @heruan, thanks for reporting this.

Indeed, we are [transpiling typescript code](https://github.com/depcheck/depcheck/blob/master/src/parser/typescript.js#L17-L54) before giving the output to our main parser (babel) and in doing that we are losing all the types... I'll see what I can do, I understand that this is not ideal for typescript users. 

In the meantime you can add those to the list of ignored dependencies.

Cheers

**Comment by ktalebian** [comment]
@rumpl any update on this?

**Comment by rumpl** [comment]
@ktalebian There were some updates with the typescript parser, depcheck will now correctly take into account the types. Try it with 0.9.0

I'll close this one, if there is still a problem, feel free to open a new issue. 

Thanks

**Comment by felixhayashi** [comment]
Unfortunately still an issue, using typescript 3.7 and depcheck 0.9.1
importing only types from a package will make depcheck mark the package as being "unused"...

**Comment by slavafomin** [comment]
I'm having the same issue. `depcheck` is reporting almost all dependencies as unused in my TypeScript project. I'm using all the latest versions.
