### ISSUE TITLE
Fails when using a relative path

### ISSUE THREAD

**Issue by Heimschmiede** [depcheck/depcheck#480]
### Bug Description
When calling depcheck from my javascript (not the cli-version) with a relative path to the folder I'd like to check then depcheck fails reading the package.json in the specified folder.
> Error: Cannot find module 'package.json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:794:15)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at readJSON (/home/thomas/tmp/node_modules/depcheck/dist/utils/index.js:26:10)
    at depcheck (/home/thomas/tmp/node_modules/depcheck/dist/index.js:74:59)
    at Object.<anonymous> (/home/thomas/tmp/index.js:28:1)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32) {

I see that depcheck is reading the package.json using `require`. This works for an absolute root path like `/path/to/project` but not for rootDirs like `.` or `./sub-project`.
The call to `require` fails with `Cannot find module 'sub-project/package.json'` because it doesn't start with a slash or a dot which results in assuming it is a module and not a path. Even when passing a leading dot as the `rootDir` it get's striped away by `path.join` in https://github.com/depcheck/depcheck/blob/master/src/index.js#L81

### Code snippets
Where the dependency is used:

```
const depcheck = require('depcheck');
 
const options = {
  ignoreBinPackage: false, // ignore the packages with bin entry
  skipMissing: false, // skip calculation of missing dependencies
  ignoreDirs: [ // folder with these names will be ignored
    'sandbox',
    'dist',
    'bower_components'
  ],
  ignoreMatches: [ // ignore dependencies that matches these globs
    'grunt-*'
  ],
};
 
depcheck('.', options, (unused) => {
  console.log(unused);
});

```

Where the dependency is listed in package.json:

```
{
  ...
  "dependencies": {
    "depcheck": "0.9.1"
  }
}
```

### Versions
 - `node -v`: v12.13.0
 - `npm -v`: 6.12.0
 - `depcheck --version`: 0.9.1

### Workaround:
use an absolute path to your project to be checked when calling `depcheck` function

#### 1: Absolute Path
When package is being called with a relative path in https://github.com/depcheck/depcheck/blob/master/src/index.js#L60
then make it absolute before code continues.
#### 2: readJson: make absolute
If the given path is a relative path then make it absolute.

**Comment by Heimschmiede** [comment]
Mhm, for me still an issue which is even very inconvenient... Would vote for reopen
