### ISSUE TITLE
Next.js webpack configuration detection failed with the following error

### ISSUE THREAD

**Issue by ravibasil** [depcheck/depcheck#545]
> Next.js webpack configuration detection failed with the following error { Error: Cannot find module 'deepmerge'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (C:\Users\Clixlogix\Desktop\ravi\mono\hub\src\config\settings.js:1:19)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3) code: 'MODULE_NOT_FOUND' } 

While running depcheck inside NextJS project

**Comment by rumpl** [comment]
hey @ravi09clix 

[depcheck is trying to `require` the config file](https://github.com/depcheck/depcheck/blob/master/src/special/webpack.js#L144) but fails, are you using `deepmerge` in your next.js configuration? Would you have a link to a repo where I can reproduce this?

**Comment by jawil003** [comment]
I have the same issue, it says distdir is missing in my `next.config.js` but I don't understand why it is needed for. I could imagine it has resolved a wrong path to the `next.config.js`? Maybe it searches in `src/` by default? Idk.
```
// next.config.js
const withPWA = require("next-pwa");

module.exports = withPWA({
  webpack: (config) => {
    return config;
  },
  pwa: {
    disable:
      process.env.NODE_ENV ===
      "development",
    dest: "public",
  },
});
```

**Comment by dapirian** [comment]
I have the same issue, would appreciate some guidance

**Comment by scottrepreneur** [comment]
This is likely happening since Next uses SWR since version 12 and can't find webpack? Any way to tie this up so it doesn't appear like an error? FWIW, doesn't seem to impact running depcheck.
