### ISSUE TITLE
False positive: ini

### ISSUE THREAD

**Issue by nils-a** [depcheck/depcheck#613]
### Bug Description

`ini` is listed a false positive (along with `https-proxy-agent`). 
I *think* this might be a duplicate of #585 (see the errors below in json-output).

### Code snippets

Where the dependency is used:

[`readConfigFile.ts` ](https://github.com/nils-a/cake-vscode/blob/feature/cleanup-deps/src/shared/utils/readConfigFile.ts)
```
import * as ini from 'ini';
# ...
return <T> ini.parse(fs.readFileSync(path.join(folderPath, fileName), 'utf-8'));
```

### Versions

- `node -v`: v14.13.1
- `npm -v`: 6.14.8
- `depcheck --version`: 1.3.1

### Extra info

steps to reproduce:
```
git clone https://github.com/nils-a/cake-vscode.git
cd cake-vscode
git checkout feature/cleanup-deps
npm i
npm run depcheck
```

`depcheck --json`:
```
{
    "dependencies": [
        "https-proxy-agent",
        "ini"
    ],
    "devDependencies": [
        "@types/ini"
    ],
    "missing": {},
    "using": {
        "depcheck": [
            "D:\\_dev\\cake-vscode\\package.json"
        ],
        "typescript": [
            "D:\\_dev\\cake-vscode\\package.json"
        ],
        "@types/node": [
            "D:\\_dev\\cake-vscode\\test\\index.ts",
            "D:\\_dev\\cake-vscode\\test\\runTest.ts",
            "D:\\_dev\\cake-vscode\\test\\shared\\utils\\handlePackagesConfig.test.ts",
            "D:\\_dev\\cake-vscode\\test\\codeLens\\codeLens.test.ts",
            "D:\\_dev\\cake-vscode\\test\\bootstrapper\\bootstrapper.test.ts",
            "D:\\_dev\\cake-vscode\\test\\bootstrapper\\memorystream.ts",
            "D:\\_dev\\cake-vscode\\src\\cakeMain.ts",
            "D:\\_dev\\cake-vscode\\src\\shared\\utils\\checkForExisting.ts",
            "D:\\_dev\\cake-vscode\\src\\shared\\utils\\getFilesPath.ts",
            "D:\\_dev\\cake-vscode\\src\\shared\\utils\\handleWriteFile.ts",
            "D:\\_dev\\cake-vscode\\src\\shared\\utils\\terminalExecutor.ts",
            "D:\\_dev\\cake-vscode\\src\\debug\\cakeDebug.ts",
            "D:\\_dev\\cake-vscode\\src\\debug\\cakeDebugCommand.ts",
            "D:\\_dev\\cake-vscode\\src\\configuration\\cakeConfiguration.ts",
            "D:\\_dev\\cake-vscode\\src\\configuration\\cakeConfigurationCommand.ts",
            "D:\\_dev\\cake-vscode\\src\\codeLens\\cakeRunTaskCommand.ts",
            "D:\\_dev\\cake-vscode\\src\\buildFile\\cakeBuildFile.ts",
            "D:\\_dev\\cake-vscode\\src\\bootstrapper\\cakeBootstrapper.ts",
            "D:\\_dev\\cake-vscode\\src\\bootstrapper\\cakeBootstrapperCommand.ts",
            "D:\\_dev\\cake-vscode\\src\\bakery\\cakeBakery.ts",
            "D:\\_dev\\cake-vscode\\src\\bakery\\cakeBakeryCommand.ts",
            "D:\\_dev\\cake-vscode\\src\\addPackage\\actions\\fetchCakePackages.ts",
            "D:\\_dev\\cake-vscode\\src\\addPackage\\actions\\handleDirectiveWithContent.ts"
        ],
        "mocha": [
            "D:\\_dev\\cake-vscode\\test\\index.ts"
        ],
        "@types/mocha": [
            "D:\\_dev\\cake-vscode\\test\\index.ts"
        ],
        "glob": [
            "D:\\_dev\\cake-vscode\\test\\index.ts"
        ],
        "@types/glob": [
            "D:\\_dev\\cake-vscode\\test\\index.ts"
        ],
        "vscode-test": [
            "D:\\_dev\\cake-vscode\\test\\runTest.ts"
        ],
        "typemoq": [
            "D:\\_dev\\cake-vscode\\test\\codeLens\\codeLens.test.ts"
        ],
        "vscode": [
            "D:\\_dev\\cake-vscode\\test\\codeLens\\codeLens.test.ts",
            "D:\\_dev\\cake-vscode\\src\\cakeMain.ts",
            "D:\\_dev\\cake-vscode\\src\\extensionSettings.ts",
            "D:\\_dev\\cake-vscode\\src\\shared\\log.ts",
            "D:\\_dev\\cake-vscode\\src\\shared\\utils\\checkForExisting.ts",
            "D:\\_dev\\cake-vscode\\src\\shared\\utils\\handleWriteFile.ts",
            "D:\\_dev\\cake-vscode\\src\\shared\\utils\\index.ts",
            "D:\\_dev\\cake-vscode\\src\\shared\\utils\\showFileQuickPick.ts",
            "D:\\_dev\\cake-vscode\\src\\shared\\utils\\terminalExecutor.ts",
            "D:\\_dev\\cake-vscode\\src\\install\\cakeInstallCommand.ts",
            "D:\\_dev\\cake-vscode\\src\\install\\actions\\index.ts",
            "D:\\_dev\\cake-vscode\\src\\install\\actions\\installCake.ts",
            "D:\\_dev\\cake-vscode\\src\\documentSymbols\\cakeDocumentSymbolProvider.ts",
            "D:\\_dev\\cake-vscode\\src\\debug\\cakeDebug.ts",
            "D:\\_dev\\cake-vscode\\src\\debug\\cakeDebugCommand.ts",
            "D:\\_dev\\cake-vscode\\src\\configuration\\cakeConfiguration.ts",
            "D:\\_dev\\cake-vscode\\src\\configuration\\cakeConfigurationCommand.ts",
            "D:\\_dev\\cake-vscode\\src\\codeLens\\cakeCodeLensProvider.ts",
            "D:\\_dev\\cake-vscode\\src\\codeLens\\cakeDebugTask.ts",
            "D:\\_dev\\cake-vscode\\src\\codeLens\\cakeRunTaskCommand.ts",
            "D:\\_dev\\cake-vscode\\src\\codeLens\\editorTools.ts",
            "D:\\_dev\\cake-vscode\\src\\buildFile\\cakeBuildFile.ts",
            "D:\\_dev\\cake-vscode\\src\\buildFile\\cakeBuildFileCommand.ts",
            "D:\\_dev\\cake-vscode\\src\\bootstrapper\\cakeBootstrapper.ts",
            "D:\\_dev\\cake-vscode\\src\\bootstrapper\\cakeBootstrapperCommand.ts",
            "D:\\_dev\\cake-vscode\\src\\bakery\\cakeBakery.ts",
            "D:\\_dev\\cake-vscode\\src\\bakery\\cakeBakeryCommand.ts",
            "D:\\_dev\\cake-vscode\\src\\addPackage\\actions\\fetchCakePackages.ts",
            "D:\\_dev\\cake-vscode\\src\\addPackage\\actions\\fetchPackageVersions.ts",
            "D:\\_dev\\cake-vscode\\src\\addPackage\\actions\\handleDirectiveWithContent.ts",
            "D:\\_dev\\cake-vscode\\src\\addPackage\\actions\\handleErrorMessage.ts",
            "D:\\_dev\\cake-vscode\\src\\addPackage\\actions\\showPackageQuickPick.ts",
            "D:\\_dev\\cake-vscode\\src\\addPackage\\actions\\showPackageSearchBox.ts",
            "D:\\_dev\\cake-vscode\\src\\addPackage\\actions\\showVersionsQuickPick.ts"
        ],
        "@types/vscode": [
            "D:\\_dev\\cake-vscode\\test\\codeLens\\codeLens.test.ts",
            "D:\\_dev\\cake-vscode\\src\\cakeMain.ts",
            "D:\\_dev\\cake-vscode\\src\\extensionSettings.ts",
            "D:\\_dev\\cake-vscode\\src\\shared\\log.ts",
            "D:\\_dev\\cake-vscode\\src\\shared\\utils\\checkForExisting.ts",
            "D:\\_dev\\cake-vscode\\src\\shared\\utils\\handleWriteFile.ts",
            "D:\\_dev\\cake-vscode\\src\\shared\\utils\\index.ts",
            "D:\\_dev\\cake-vscode\\src\\shared\\utils\\showFileQuickPick.ts",
            "D:\\_dev\\cake-vscode\\src\\shared\\utils\\terminalExecutor.ts",
            "D:\\_dev\\cake-vscode\\src\\install\\cakeInstallCommand.ts",
            "D:\\_dev\\cake-vscode\\src\\install\\actions\\index.ts",
            "D:\\_dev\\cake-vscode\\src\\install\\actions\\installCake.ts",
            "D:\\_dev\\cake-vscode\\src\\documentSymbols\\cakeDocumentSymbolProvider.ts",
            "D:\\_dev\\cake-vscode\\src\\debug\\cakeDebug.ts",
            "D:\\_dev\\cake-vscode\\src\\debug\\cakeDebugCommand.ts",
            "D:\\_dev\\cake-vscode\\src\\configuration\\cakeConfiguration.ts",
            "D:\\_dev\\cake-vscode\\src\\configuration\\cakeConfigurationCommand.ts",
            "D:\\_dev\\cake-vscode\\src\\codeLens\\cakeCodeLensProvider.ts",
            "D:\\_dev\\cake-vscode\\src\\codeLens\\cakeDebugTask.ts",
            "D:\\_dev\\cake-vscode\\src\\codeLens\\cakeRunTaskCommand.ts",
            "D:\\_dev\\cake-vscode\\src\\codeLens\\editorTools.ts",
            "D:\\_dev\\cake-vscode\\src\\buildFile\\cakeBuildFile.ts",
            "D:\\_dev\\cake-vscode\\src\\buildFile\\cakeBuildFileCommand.ts",
            "D:\\_dev\\cake-vscode\\src\\bootstrapper\\cakeBootstrapper.ts",
            "D:\\_dev\\cake-vscode\\src\\bootstrapper\\cakeBootstrapperCommand.ts",
            "D:\\_dev\\cake-vscode\\src\\bakery\\cakeBakery.ts",
            "D:\\_dev\\cake-vscode\\src\\bakery\\cakeBakeryCommand.ts",
            "D:\\_dev\\cake-vscode\\src\\addPackage\\actions\\fetchCakePackages.ts",
            "D:\\_dev\\cake-vscode\\src\\addPackage\\actions\\fetchPackageVersions.ts",
            "D:\\_dev\\cake-vscode\\src\\addPackage\\actions\\handleDirectiveWithContent.ts",
            "D:\\_dev\\cake-vscode\\src\\addPackage\\actions\\handleErrorMessage.ts",
            "D:\\_dev\\cake-vscode\\src\\addPackage\\actions\\showPackageQuickPick.ts",
            "D:\\_dev\\cake-vscode\\src\\addPackage\\actions\\showPackageSearchBox.ts",
            "D:\\_dev\\cake-vscode\\src\\addPackage\\actions\\showVersionsQuickPick.ts"
        ],
        "xml2js": [
            "D:\\_dev\\cake-vscode\\src\\shared\\utils\\handlePackagesConfig.ts"
        ],
        "@types/xml2js": [
            "D:\\_dev\\cake-vscode\\src\\shared\\utils\\handlePackagesConfig.ts"
        ],
        "request": [
            "D:\\_dev\\cake-vscode\\src\\debug\\cakeDebug.ts",
            "D:\\_dev\\cake-vscode\\src\\configuration\\cakeConfiguration.ts",
            "D:\\_dev\\cake-vscode\\src\\bootstrapper\\cakeBootstrapper.ts",
            "D:\\_dev\\cake-vscode\\src\\bakery\\cakeBakery.ts"
        ],
        "adm-zip": [
            "D:\\_dev\\cake-vscode\\src\\debug\\cakeDebug.ts",
            "D:\\_dev\\cake-vscode\\src\\bakery\\cakeBakery.ts"
        ],
        "node-fetch": [
            "D:\\_dev\\cake-vscode\\src\\addPackage\\actions\\fetchCakePackages.ts",
            "D:\\_dev\\cake-vscode\\src\\addPackage\\actions\\fetchPackageVersions.ts",
            "D:\\_dev\\cake-vscode\\src\\addPackage\\actions\\handleSearchResponse.ts",
            "D:\\_dev\\cake-vscode\\src\\addPackage\\actions\\handleVersionsResponse.ts"
        ],
        "@types/node-fetch": [
            "D:\\_dev\\cake-vscode\\src\\addPackage\\actions\\fetchCakePackages.ts",
            "D:\\_dev\\cake-vscode\\src\\addPackage\\actions\\fetchPackageVersions.ts",
            "D:\\_dev\\cake-vscode\\src\\addPackage\\actions\\handleSearchResponse.ts",
            "D:\\_dev\\cake-vscode\\src\\addPackage\\actions\\handleVersionsResponse.ts"
        ],
        "byline": [
            "D:\\_dev\\cake-vscode\\src\\addPackage\\actions\\handleDirectiveWithContent.ts"
        ],
        "@types/byline": [
            "D:\\_dev\\cake-vscode\\src\\addPackage\\actions\\handleDirectiveWithContent.ts"
        ]
    },
    "invalidFiles": {
        "D:\\_dev\\cake-vscode\\test\\addPackage\\actions\\handleSearchResponse.test.ts": "SyntaxError: Unexpected token, expected \"}\" (8:64)\n    at Object._raise (D:\\_dev\\cake-vscode\\node_modules\\@babel\\parser\\lib\\index.js:748:17)\n    at Object.raiseWithData (D:\\_dev\\cake-vscode\\node_modules\\@babel\\parser\\lib\\index.js:741:17)\n    at Object.raise (D:\\_dev\\cake-vscode\\node_modules\\@babel\\parser\\lib\\index.js:735:17)\n    at Object.unexpected (D:\\_dev\\cake-vscode\\node_modules\\@babel\\parser\\lib\\index.js:9097:16)\n    at Object.expect (D:\\_dev\\cake-vscode\\node_modules\\@babel\\parser\\lib\\index.js:9083:28)\n    at Object.jsxParseExpressionContainer (D:\\_dev\\cake-vscode\\node_modules\\@babel\\parser\\lib\\index.js:4613:10)\n    at Object.jsxParseElementAt (D:\\_dev\\cake-vscode\\node_modules\\@babel\\parser\\lib\\index.js:4704:36)\n    at Object.jsxParseElementAt (D:\\_dev\\cake-vscode\\node_modules\\@babel\\parser\\lib\\index.js:4689:32)\n    at Object.jsxParseElement (D:\\_dev\\cake-vscode\\node_modules\\@babel\\parser\\lib\\index.js:4747:17)\n    at Object.parseExprAtom (D:\\_dev\\cake-vscode\\node_modules\\@babel\\parser\\lib\\index.js:4754:19)",
        "D:\\_dev\\cake-vscode\\src\\shared\\utils\\getFetchOptions.ts": "SyntaxError: Unexpected token, expected \"}\" (53:9)\n    at Object._raise (D:\\_dev\\cake-vscode\\node_modules\\@babel\\parser\\lib\\index.js:748:17)\n    at Object.raiseWithData (D:\\_dev\\cake-vscode\\node_modules\\@babel\\parser\\lib\\index.js:741:17)\n    at Object.raise (D:\\_dev\\cake-vscode\\node_modules\\@babel\\parser\\lib\\index.js:735:17)\n    at Object.unexpected (D:\\_dev\\cake-vscode\\node_modules\\@babel\\parser\\lib\\index.js:9097:16)\n    at Object.expect (D:\\_dev\\cake-vscode\\node_modules\\@babel\\parser\\lib\\index.js:9083:28)\n    at Object.jsxParseExpressionContainer (D:\\_dev\\cake-vscode\\node_modules\\@babel\\parser\\lib\\index.js:4613:10)\n    at Object.jsxParseElementAt (D:\\_dev\\cake-vscode\\node_modules\\@babel\\parser\\lib\\index.js:4704:36)\n    at Object.jsxParseElementAt (D:\\_dev\\cake-vscode\\node_modules\\@babel\\parser\\lib\\index.js:4689:32)\n    at Object.jsxParseElement (D:\\_dev\\cake-vscode\\node_modules\\@babel\\parser\\lib\\index.js:4747:17)\n    at Object.parseExprAtom (D:\\_dev\\cake-vscode\\node_modules\\@babel\\parser\\lib\\index.js:4754:19)",
        "D:\\_dev\\cake-vscode\\src\\shared\\utils\\readConfigFile.ts":"SyntaxError: Unexpected token (55:4)\n    at Object._raise (D:\\_dev\\cake-vscode\\node_modules\\@babel\\parser\\lib\\index.js:748:17)\n    at Object.raiseWithData (D:\\_dev\\cake-vscode\\node_modules\\@babel\\parser\\lib\\index.js:741:17)\n    at Object.raise (D:\\_dev\\cake-vscode\\node_modules\\@babel\\parser\\lib\\index.js:735:17)\n    at Object.unexpected (D:\\_dev\\cake-vscode\\node_modules\\@babel\\parser\\lib\\index.js: 9097: 16)\n    at Object.parseExprAtom (D:\\_dev\\cake-vscode\\node_modules\\@babel\\parser\\lib\\index.js: 10548: 20)\n    at Object.parseExprAtom (D:\\_dev\\cake-vscode\\node_modules\\@babel\\parser\\lib\\index.js: 4759: 20)\n    at Object.parseExprSubscripts (D:\\_dev\\cake-vscode\\node_modules\\@babel\\parser\\lib\\index.js: 10122: 23)\n    at Object.parseUpdate (D:\\_dev\\cake-vscode\\node_modules\\@babel\\parser\\lib\\index.js: 10102: 21)\n    at Object.parseMaybeUnary (D:\\_dev\\cake-vscode\\node_modules\\@babel\\parser\\lib\\index.js: 10091: 17)\n    at Object.parseMaybeUnary (D:\\_dev\\cake-vscode\\node_modules\\@babel\\parser\\lib\\index.js: 7122: 20)"},"invalidDirs":{}}
```

**Comment by rumpl** [comment]
@nils-a I wish all the issues created were as thorough as yours is, thank you!

I will take a look

**Comment by rumpl** [comment]
Ok so the thing is that we are using babel to parse typescript files and one of the plugins loaded is the `jsx` one and it's causing problems with the `readConfig.ts` file because of `return <T>(`, if I remove the jsx plugin it all works fine, gotta find a nice solution, this might be a bug in babel and its typescript/jsx parser.

**Comment by rumpl** [comment]
A temporary solution for you would be to change your code to 

```
return ini.parse(
    fs.readFileSync(path.join(folderPath, fileName), "utf-8")
) as T;
```

[It would seem that using `as` is the preferred way](https://acdcjunior.github.io/typescript-cast-object-to-other-type-or-instanceof.html) because `<T>` cast is [not available for tsx files](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-1-6.html#new-tsx-file-extension-and-as-operator).

Now I could split the current typescript parser into two parsers, one for ts and one for tsx files, guess I should huh.

**Comment by nils-a** [comment]
@rumpl the code base is a bit older and I am hesitant to cleanup all at once :)

Could I remove the `jsx` plugin via configuration? (I don't need that currently)

**Comment by rumpl** [comment]
I understand your reluctance, it’s only natural :)

You can’t do anything with the cinfiguration easily unfortunately. It’s getting late here, I’ll find a solution for you tomorrow. Eiteher with a new parser or some mix of your own parser and configuration. I’m sure this is not the only case where this happens. Maybe I can change the ts parser to try once with the jsx plugin and if it fails retry without. In any case there are different things we can do to make this work for you. Will keep you informed

**Comment by nils-a** [comment]
It's getting late here, too. We're in the same TZ :-)
Thanks for the work you put in this 🙇

**Comment by nils-a** [comment]
@rumpl I re-visisted the usage of casting with `<>` vs casting with `as` and in the end it was only 6 places in 3 files to modify (two of those casts were actually not needed) so I went along and made the changes. 
No errors are reported in `depcheck --json` and no false positives anymore.

Thanks again for all your help!

(I'll leave this open so you have a reminder on why you wanted to re-work the ts parser 😉  )
