### ISSUE TITLE
Next.js webpack configuration detection failed

### ISSUE THREAD

**Issue by sgarnotel** [depcheck/depcheck#637]
### Bug Description

An error message is displayed related to nextjs webpack configuration:
```
Next.js webpack configuration detection failed with the following error TypeError: Cannot read property 'ignored' of undefined
    at Object.webpack (/***/node_modules/next-transpile-modules/src/next-transpile-modules.js:284:34)
    at Object.webpack (/***/node_modules/@zeit/next-less/index.js:41:27)
    at loadNextWebpackConfig (/***/node_modules/depcheck/dist/special/webpack.js:154:25)
    at parseWebpack (/***/node_modules/depcheck/dist/special/webpack.js:184:27)
    at getDependencies (/***/node_modules/depcheck/dist/check.js:71:24)
    at /***/node_modules/depcheck/dist/check.js:97:32
    at Array.map (<anonymous>)
    at checkFile (/***/node_modules/depcheck/dist/check.js:97:18)
    at ReaddirpStream.<anonymous> (/***/node_modules/depcheck/dist/check.js:126:24)
    at ReaddirpStream.emit (node:events:365:28) Support for this feature is new and experimental, please report issues at https://github.com/depcheck/depcheck/issues
```

### Code snippets

Where the dependency is used:

In the `next.config.js`:
```
const path = require('path')

const withTM = require('next-transpile-modules')(['three'])
const withLess = require('@zeit/next-less')

const sentryConfig = require('./config/sentry')

const basePath = ''

module.exports = withLess({
  paths: [path.resolve(__dirname, 'node_modules')],
  lessLoaderOptions: {
    javascriptEnabled: true
  },
  ...withTM({
    webpack: (config, { isServer, webpack }) => {
      if (!isServer) {
        config.resolve.alias['@sentry/node'] = '@sentry/browser'
      }

      config.node = {
        __dirname: true
      }

      config.plugins.push(new webpack.IgnorePlugin(/\/__tests__\//))

      return config
    },
    env: {
      SENTRY_DSN: sentryConfig.DSN
    },
    basePath
  })
})
```

Where the dependency is listed in package.json:

```
"dependencies": {
    "electron-serve": "1.1.0",
    "electron-store": "8.0.0"
  },
  "devDependencies": {
    "@ant-design/icons": "4.6.2",
    "@babel/cli": "7.13.16",
    "@babel/core": "7.14.0",
    "@babel/preset-typescript": "7.13.0",
    "@hapi/iron": "6.0.0",
    "@sentry/browser": "6.3.4",
    "@sentry/node": "6.3.4",
    "@wojtekmaj/enzyme-adapter-react-17": "0.6.1",
    "@zeit/next-less": "1.0.1",
    "antd": "4.15.3",
    "archiver": "5.3.0",
    "babel-jest": "26.6.3",
    "babel-loader": "8.2.2",
    "babel-plugin-import": "1.13.3",
    "babel-plugin-module-resolver": "4.1.0",
    "cookie": "0.4.1",
    "cors": "2.8.5",
    "deep-object-diff": "1.1.0",
    "depcheck": "1.4.0",
    "ejs": "3.1.6",
    "electron": "12.0.5",
    "electron-builder": "22.10.5",
    "enzyme": "3.11.0",
    "express": "4.17.1",
    "foodoc": "0.0.9",
    "http-errors": "1.8.0",
    "is-docker": "2.2.1",
    "is-electron": "2.2.0",
    "jest": "26.6.3",
    "jsdoc": "3.6.6",
    "less": "4.1.1",
    "lodash.merge": "4.6.2",
    "mailersend": "1.0.2",
    "next": "10.2.0",
    "next-transpile-modules": "7.0.0",
    "nextron": "6.0.6",
    "node-fetch": "2.6.1",
    "passport": "0.4.1",
    "passport-local": "1.0.0",
    "pg": "8.6.0",
    "pg-native": "3.0.0",
    "prettier": "2.2.1",
    "react": "17.0.2",
    "react-dom": "17.0.2",
    "react-redux": "7.2.4",
    "recharts": "2.0.9",
    "redux": "4.1.0",
    "redux-devtools-extension": "2.13.9",
    "redux-persist": "6.0.0",
    "rimraf": "3.0.2",
    "swr": "0.5.5",
    "three": "0.128.0",
    "three-to-glb": "./modules/three-to-glb/",
    "url-join": "4.0.1"
  }
```

### Versions

- `node -v`: 16.1.0
- `npm -v`: 7.12.0
- `yarn -v`: 1.22.10
- `depcheck --version`: 1.4.0

### Extra info

I use `yarn` and not `npm`.

**Comment by rumpl** [comment]
@sgarnotel thanks for openning this issue, is there a repo somewhere that reproduces this error?

**Comment by sgarnotel** [comment]
I have created this minimal example https://github.com/Airthium/depcheck-issue
When you run `yarn depcheck` the error occurs.

**Comment by rumpl** [comment]
Thanks! This however seems like a bug in [the `next-transpile-modules` code](https://github.com/martpie/next-transpile-modules/pull/180)
