### ISSUE TITLE
Fails to parse `serverless.yml` if it contains certain CloudFormation syntax

### ISSUE THREAD

**Issue by smbkr** [depcheck/depcheck#639]
### Bug Description

Depcheck fails to parse `serverless.yml` when using the "serverless" special, and a `serverless.yml` file which contains certain CloudFormation syntax.

### Code snippets

The error:

```
YAMLException: unknown tag !<!Ref> at line 23, column 26:
          Value: !Ref myTopic
                             ^
    at generateError (/Users/stuart.baker1/Projects/depcheck-serverless-repro/node_modules/js-yaml/lib/js-yaml/loader.js:167:10)
    at throwError (/Users/stuart.baker1/Projects/depcheck-serverless-repro/node_modules/js-yaml/lib/js-yaml/loader.js:173:9)
    at composeNode (/Users/stuart.baker1/Projects/depcheck-serverless-repro/node_modules/js-yaml/lib/js-yaml/loader.js:1434:7)
    at readBlockMapping (/Users/stuart.baker1/Projects/depcheck-serverless-repro/node_modules/js-yaml/lib/js-yaml/loader.js:1089:11)
    at composeNode (/Users/stuart.baker1/Projects/depcheck-serverless-repro/node_modules/js-yaml/lib/js-yaml/loader.js:1359:12)
    at readBlockMapping (/Users/stuart.baker1/Projects/depcheck-serverless-repro/node_modules/js-yaml/lib/js-yaml/loader.js:1089:11)
    at composeNode (/Users/stuart.baker1/Projects/depcheck-serverless-repro/node_modules/js-yaml/lib/js-yaml/loader.js:1359:12)
    at readBlockMapping (/Users/stuart.baker1/Projects/depcheck-serverless-repro/node_modules/js-yaml/lib/js-yaml/loader.js:1089:11)
    at composeNode (/Users/stuart.baker1/Projects/depcheck-serverless-repro/node_modules/js-yaml/lib/js-yaml/loader.js:1359:12)
    at readBlockMapping (/Users/stuart.baker1/Projects/depcheck-serverless-repro/node_modules/js-yaml/lib/js-yaml/loader.js:1089:11)
```

Snippet from `serverless.yml`:

```yml
resources:
  Outputs:
    myTopicARN:
      Description: 'Arn for my SNS Topic'
      Value: !Ref myTopic
```

I haven't included where the dependency is used or listed in `package.json` because it doesn't even get that far, but they are included in the repo linked below.

### Versions

- `node -v`: v12.22.1
- `npm -v`: 6.14.12
- `depcheck --version`: 1.2.0
- `yarn --version`: 1.22.5

### Extra info

I have created a repo with a minimal repro of the issue: https://github.com/smbkr/depcheck-sls-repro

**Comment by smbkr** [comment]
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-getatt.html

Using the full syntax instead of shorthand as described in the above for all CF functions works around the issue.

I'll close this as I don't think it's worth adding support to depcheck when there's a syntactically correct way to use CF in serverless.yml.

**Comment by taschmidt** [comment]
I think this should be reopened since it makes the serverless functionality pretty useless. We make extensive use of the short form syntax in our configs and it's valid in `serverless.yml`.
