### ISSUE TITLE
Peer dependencies still showing as "unused" after being installed

### ISSUE THREAD

**Issue by chrisbobbe** [depcheck/depcheck#663]
### Bug Description

Following up from https://github.com/depcheck/depcheck/issues/341#issuecomment-813430765, when I noticed a similar-looking issue. 🙂 If I've installed a package because of peer-dependency requirements, I don't expect it to show up under "unused".

Please see https://github.com/chrisbobbe/depcheck-repro for a minimal reproduction. I'm using Yarn 1.22.10.

In that project, which has this short `package.json`—

```json
{
  "name": "depcheck-repro",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "dependencies": {
    "@octokit/core": "^3.5.1",
    "depcheck": "^1.4.2",
    "flow-typed": "^3.3.1"
  }
}
```

—I

1. Ran `yarn`
2. Ran `yarn depcheck --ignore-bin-package=true` and got this output:

   ```
   Unused dependencies
   * @octokit/core
   error Command failed with exit code 255.
   ```

   (Or, with `--json`, I got
   
   ```
   {"dependencies":["@octokit/core"],"devDependencies":[],"missing":{},"using":{},"invalidFiles":{},"invalidDirs":{}}
   ```
   
   )

3. But I didn't expect to see @octokit/core there. I installed it because of peer-dependency constraints. In particular, if I `yarn remove @octokit/core`, I get this output:

   ```
   yarn remove v1.22.10
   [1/2] 🗑  Removing module @octokit/core...
   [2/2] 🔨  Regenerating lockfile and installing missing dependencies...
   warning "flow-typed > @octokit/rest > @octokit/plugin-request-log@1.0.4" has unmet peer dependency 
   "@octokit/core@>=3".
   success Uninstalled packages.
   ✨  Done in 0.77s.
   ```

### Versions

- `node -v`: v12.18.3
- `npm -v`: N/A
- `yarn -v`: 1.22.10
- `depcheck --version`: 1.4.2

**Comment by hakimio** [comment]
Same issue here.
@rumpl any progress on this?

**Comment by efriandika** [comment]
This feature works as expected.
Please check your `node_modules/some-libs/package.json` if it has peerDependencies info or no. Because this libs rely on peerDependencies info in `node_modules/some-libs/package.json`

**Comment by chrisbobbe** [comment]
Thanks for the response! 🙂

> This feature works as expected.

Do you mean the bug hasn't reproduced when you've followed my instructions with my sample project? 🙂 Or do you mean you don't think the behavior I'm describing is a bug (and why)?

> Please check your `node_modules/some-libs/package.json` if it has peerDependencies info or no. Because this libs also rely on it in order to calculate the un used dependencies.

Here is the relevant part of node_modules/@octokit/plugin-request-log/package.json:

```json
  "peerDependencies": {
    "@octokit/core": ">=3"
  },
```

(This is what I expect to see there, based on the peer-dep warning I quoted in the reproduction recipe.)

**Comment by efriandika** [comment]
There is something wrong with your repo.

All of your [dependencies](https://github.com/chrisbobbe/depcheck-repro/blob/main/package.json#L6) are unused. Because you never use it in `import { Octokit } from "@octokit/core"` or `require("@octokit/core")`

Try to add this:
index.js:
```
import { Octokit } from "@octokit/core";
```

**Comment by chrisbobbe** [comment]
Ah OK, thanks for that explanation! I think we're working with different meanings of "unused".

In the meaning I have in mind (and the author of https://github.com/depcheck/depcheck/issues/341#issuecomment-813430765), I say that I'm "using" `@octokit/core` to satisfy peer-dependency requirements, by including it in `dependencies`. That's why I said this:

> If I've installed a package because of peer-dependency requirements, I don't expect it to show up under "unused".

I don't have any reason to "use" `@octokit/core` the way I think you have in mind: I don't need to import it in my own code. Still, even without importing it, it would be a bug to remove `@octokit/core` from `dependencies`. (See quoted peer-dep warning.) That's why I was surprised to see `depcheck` telling me it's unused, which implies that it's fine to remove.

**Comment by efriandika** [comment]
> Ah OK, thanks for that explanation! I think we're working with different meanings of "unused".

> I don't have any reason to "use" @octokit/core the way I think you have in mind: I don't need to import it in my own code. Still, even without importing it, it would be a bug to remove @octokit/core from dependencies. (See quoted peer-dep warning.) That's why I was surprised to see depcheck telling me it's unused, which implies that it's fine to remove. 

**Your https://github.com/chrisbobbe/depcheck-repro is NOT correct.** 

Please keep in mind: 
* This libs detect unused libs if it is not imported in any files. 
* If you import a libs, and it has peerDependencies, its peer dependencies WILL NOT marked as unused.

Example:
If you have a dependency to `X` which X has peerDependencies to `Y`. Both of them will be considered as used.
But, please keep in mind: you must import X at least in a file.

For peer dependencies, it works as expected. Try this [simple test case](https://github.com/depcheck/depcheck/tree/main/test/fake_modules/peer_dep) to make it clear for you

**Comment by rumpl** [comment]
@efriandika thanks for jumping in and explaining the issue. I guess we can close this now right?

**Comment by efriandika** [comment]
> Do you understand why I think it's not a mistake that an import of @octokit/core appears nowhere in my repro? I hope this is explained at #663 (comment).

???? 

Have you read the all aspect of the prev comments?

**Comment by hakimio** [comment]
@efriandika you are clearly the one lacking reading comprehension here. Just stop. You are not helping anyone.

**Comment by rumpl** [comment]
Ok people, please calm down, promise I'll take a look at this issue on Monday, please stop commenting if you want to be rude. Sorry everyone for not being more involved with this issue. <3

**Comment by hakimio** [comment]
@rumpl any progress on the issue?

**Comment by hdidier** [comment]
Wanted to add that I'm also seeing this issue and looking forward to a resolution.

**Comment by dobesv** [comment]
I think the rules of npm are such that if a module has to satisfy the peer dependencies of its dependencies using a dependency or propagate them upwards using a peer dependency.

If you have packages that aren't properly re-exporting the peer dependencies they don't satisfy that is likely a bug in that package, not depcheck, and should be reported there.

At least, that's my interpration based on the copious complaints I get from yarn about packages not satisfying their peer dependencies ...

**Comment by flying-sheep** [comment]
In my case, everything seems to be correctly specified:

```json
{
	"name": "phil.red",
	"devDependencies": {
		"@rollup/plugin-typescript": "^11.0.0",
		"typescript": "^4.9.4"
	},
	"packageManager": "yarn@3.3.0"
}
```

Since when I remove `typescript`, I see

```
➤ YN0002: │ phil.red@workspace:. doesn't provide typescript (pbdc8f), requested by @rollup/plugin-typescript
```

But when I run `depcheck`, I get this:

```console
$ yarn dlx depcheck
Unused devDependencies
* typescript
```

What’s wrong?

**Comment by flying-sheep** [comment]
Still relevant

**Comment by dobesv** [comment]
Regarding https://github.com/chrisbobbe/depcheck-repro specifically, none of the dependencies are used.  So it's not a valid reproduction.

```
$ yarn depcheck
Unused dependencies
* @octokit/core
* depcheck
* flow-typed
$ cat package.json
{
  "name": "depcheck-repro",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "dependencies": {
    "@octokit/core": "^3.5.1",
    "depcheck": "^1.4.2",
    "flow-typed": "^3.3.1"
  }
}
$ ls
node_modules  package.json  yarn.lock

```

This is because there are no source files.

Note that if I remove the `@octokit/core` dependency, yarn does complain about a missing peer dependency, but not for the top-level project:

```
$ yarn remove @octokit/core
➤ YN0000: ┌ Resolution step
➤ YN0002: │ @octokit/rest@npm:16.43.2 doesn't provide @octokit/core (p84523), requested by @octokit/plugin-request-log
➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code
➤ YN0000: └ Completed
➤ YN0000: ┌ Fetch step
➤ YN0019: │ @octokit-core-npm-3.5.1-a933dedcf7-67179739fc.zip appears to be unused - removing
➤ YN0019: │ @octokit-graphql-npm-4.6.4-6d6d41e43c-5841e13e78.zip appears to be unused - removing
➤ YN0000: └ Completed
➤ YN0000: ┌ Link step
➤ YN0000: └ Completed
➤ YN0000: Done with warnings in 0s 292ms
```

And in fact when I look at `@octokit/rest` it neither provides the dependency nor includes it in `peerDependencies`:

```
> require('@octokit/plugin-request-log/package.json').peerDependencies
{ '@octokit/core': '>=3' }
> require('@octokit/rest/package.json').peerDependencies
undefined
> Object.keys(require('@octokit/rest/package.json').dependencies)
[
  '@octokit/auth-token',
  '@octokit/plugin-paginate-rest',
  '@octokit/plugin-request-log',
  '@octokit/plugin-rest-endpoint-methods',
  '@octokit/request',
  '@octokit/request-error',
  'atob-lite',
  'before-after-hook',
  'btoa-lite',
  'deprecation',
  'lodash.get',
  'lodash.set',
  'lodash.uniq',
  'octokit-pagination-methods',
  'once',
  'universal-user-agent'
]
```

So that specific example is actually not a problem with depcheck, it's a problem with the package.

**Comment by dobesv** [comment]
With respect to the `@chakra-ui/theme` import issue, I tried to reproduce this but I didn't get the same issue:

```
$ yarn
➤ YN0000: ┌ Resolution step
➤ YN0000: └ Completed
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed
➤ YN0000: ┌ Link step
➤ YN0000: └ Completed
➤ YN0000: Done in 0s 116ms
17:05:23 ~/projects/third-party/depcheck-repro (main)*
$ cat package.json
{
  "name": "depcheck-repro",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "dependencies": {
    "@chakra-ui/styled-system": "^2.9.1",
    "@chakra-ui/theme": "^3.1.2",
    "depcheck": "^1.4.2"
  },
  "scripts": {
    "depcheck": "depcheck"
  }
}
17:05:29 ~/projects/third-party/depcheck-repro (main)*
$ cat test.js
import "@chakra-ui/theme";
17:05:47 ~/projects/third-party/depcheck-repro (main)*
$ yarn depcheck
No depcheck issue
```

Maybe something has changed with the dependencies of `@chakra-ui`, though.

Does anyone have any other steps to reproduce this issue currently?

**Comment by dobesv** [comment]
In investigating the issue with `@rollup/plugin-typescript` I did run into this error:

```
> require('@rollup/plugin-typescript/package.json').peerDependencies
Uncaught:
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './package.json' is not defined by "exports" in /home/dobes/projects/third-party/depcheck-repro/node_modules/@rollup/plugin-typescript/package.json
    at __node_internal_captureLargerStackTrace (node:internal/errors:490:5)
    at new NodeError (node:internal/errors:399:5)
    at exportsNotFound (node:internal/modules/esm/resolve:361:10)
    at packageExportsResolve (node:internal/modules/esm/resolve:697:9)
    at resolveExports (node:internal/modules/cjs/loader:565:36)
    at Module._findPath (node:internal/modules/cjs/loader:634:31)
    at Module._resolveFilename (node:internal/modules/cjs/loader:1061:27)
    at Module._load (node:internal/modules/cjs/loader:920:27)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}
```

Currently it looks like `depcheck` uses `require` to load the `package.json` of dependencies to detect `peerDependencies`.  So I suspect the issue here is that when the dependency does not export `package.json` properly, `depcheck` cannot get that information and acts as if there are no `peerDependencies` or bin scripts.

If this same issue explains any other issues people are having I would suggest opening a new issue along the lines of better handling packages that do not export `package.json`.  I think the `peerDependencies` handling does seem to be correct in the absence of these issues, even for peers of peers.

**Comment by flying-sheep** [comment]
Thank you for investigating.

> I suspect the issue here is that when the dependency does not export package.json properly

I don’t think that’s proper at all. `"exports`" is a field *in* `package.json`, so when you read it, you’ve already found `package.json`. Therefore it doesn’t make sense to add that file to the exports.

Therefore, if `require` changed behavior so you can’t use it for files not listed in `"exports"`, then it’s the wrong tool for reading `package.json`.

**Comment by dobesv** [comment]
> I don’t think that’s proper at all. "exports" is a field in package.json, so when you read it, you’ve already found package.json. Therefore it doesn’t make sense to add that file to the exports.

Hmm interesting point.  Unfortunately the `require.resolve` function that "finds" package.json won't tell us where it found it, it only lets us lookup exports in the module.  Without exporting `package.json` I'm not sure there's any standard way to find the `package.json` of a package without knowing the internals of the module resolution system you are using at the time.

#760 does get around this by making certain (probably safe) assumptions about the package directory structure, so at least it has resolved that case where peer dependencies are not detected.  But it does feel like a bit of a hack.

I guess ideally `require.resolve` would have done this for us by supporting a lookup of `package.json` specifically, or there would be some other method of requesting package metadata.

**Comment by dobesv** [comment]
And come to think of it, looking up an exported `package.json` isn't really a "standard" way to find that, either, it's also kind of a hack even if it often works.

**Comment by chrisbobbe** [comment]
> Regarding https://github.com/chrisbobbe/depcheck-repro specifically, none of the dependencies are used. So it's not a valid reproduction.
>
> This is because there are no source files.

My proposal is to use a definition of "used" that includes "used to resolve peer-dependency warnings in Yarn output". If you grant that definition, then my reproduction is valid and shows a real bug. You don't grant that definition—you looked for source files—and so you don't see any bug. That's up to you, but like similar responses upthread, your quarrel is with my definition and what qualifies as a bug, and not with how well or badly my reproduction demonstrates what I said it does.

> And in fact when I look at `@octokit/rest` it neither provides the dependency nor includes it in `peerDependencies`:

I appreciate that `@octokit/rest` is at fault here, and that that fact is clearer in the output of (I think) the newer version of Yarn that you're using. Nevertheless, as you have seen yourself in your investigation there, a direct `@octokit/core` dependency can be used to resolve that warning from Yarn. (Without `@octokit/core`, the warning appears; with it, the warning does not appear.)

I don't expect to have time to argue the point further because my project requirements have changed; I don't need `depcheck` anymore. It seems like this issue will be closed, and if so, I would respectfully suggest that people save their effort trying to reproduce behavior that has already been demonstrated. In retrospect, I probably could have done better by offering a PR, but as I said, my project requirements have changed.

**Comment by dobesv** [comment]
> My proposal is to use a definition of "used" that includes "used to resolve peer-dependency warnings in Yarn output".
> You don't grant that definition—you looked for source files—and so you don't see any bug.

Depcheck specifically is designed to check which dependencies are used in source files (or maybe scripts in package.json), so if there are no source files, no dependencies are used.  So reporting all dependencies as unused seems correct in this case, at least to me.

I did go ahead and add a source file to try and reproduce the actual issue there, and found it was an issue with the reported dependencies of the packages.

I can see how it might be nice if depcheck had more similar behavior as yarn, though.  I'm not sure why adding the dependency makes yarn happy even though the dependencies listed for `@octokit/rest` are incorrect.

However, it's also not clear it's worth the trouble to figure that out and make this enhancement to `depcheck` ...

I should probably also clarify I'm not a `depcheck` maintainer and I don't have commit access or any authority to veto your request here.

I was investigating as an independent volunteer in the hopes of finding a real bug to fix as we do use depcheck and these weird cases are a thorn in our side sometimes.

**Comment by dobesv** [comment]
So what logic would you use where given a package name you want to get its `package.json` in a good way?

> `JSON.parse(fs.readFileSync('./package.json'))`

This seems to be reading from the current directory, but the issue we are discussing here is about getting `package.json` from a dependency.

**Comment by dobesv** [comment]
I guess my observation here is that there is no correct way to get the package.json for a dependency that I am aware of, you just have to pick your hack.  It looks like the latest version of `depcheck` employs these hacks:

1. Resolve the path to the "main" module of the dependency using `require.resolve(dependency)` and scan upwards looking for `package.json` in a parent folder.  This doesn't work for packages that don't export an index / top-level module
2. Resolve the `package.json` file using `require.resolve(dependency+"/package.json")`.  This doesn't work for packages that don't have `package.json` in their exports.

Neither of these are correct, but they work.  In combination they probably have pretty good coverage, but there could still be modules out there that do not export a top-level module and also do not export `package.json`.

**Comment by flying-sheep** [comment]
> I guess my observation here is that there is no correct way to get the package.json for a dependency that I am aware of, you just have to pick your hack. 

What makes you think that the “scan upwards” solution is incorrect? Just because it looks overly complex doesn’t mean it’s not a correct solution.

**Comment by dobesv** [comment]
> the actual path would need to be determined

Well, yes that's exactly the problem here.

> What makes you think that the “scan upwards” solution is incorrect?

I don't think it's not guaranteed that `require.resolve('some-package')` and scanning upwards for the first `package.json` will give exactly the `package.json` that you want.  There's nothing in the spec that I am aware that would guarantee this.  Consider if the package.json is like:

```
"name": "example",
"exports": {
"foo": "./dist/foo.js",
"bar":" ./dist/bar.js"
}
```

In this case there's no top-level export, you cannot `require('example')` alone, I tested this just now with a package in our monorepo:

```
> require('...')
Uncaught:
Error: No "exports" main defined in /home/dobes/.../package.json imported from /home/dobes/projects/...
Require stack:
- <repl>
    at require$$0.Module._resolveFilename (/home/dobes/projects/formative/app/.pnp.cjs:70884:13)
    at require$$0.Module._load (/home/dobes/projects/formative/app/.pnp.cjs:70734:42)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
```

**Comment by dobesv** [comment]
> Wait, it still does require.resolve(`${dependency}/package.json`)? Where?

https://github.com/depcheck/depcheck/blob/main/src/utils/module-root.js#L17

It seems like a LOT of packages that use `exports` also export `package.json` and I think this technique still works for packages without `exports` since I guess the lookup just proceeds from the top folder of the module or something.

**Comment by dobesv** [comment]
Actually I noticed that when depcheck finds a `package.json` it uses an actual import from the source code if it has one:

https://github.com/depcheck/depcheck/blob/main/src/utils/module-root.js#L15

This approach will work even without a main export in the package when using the "scan upwards for package.json" method.

Packages that are only mentioned by name in configuration files will *typically* use the main export, so the technique should work most of the time.  At least for purposes of `depcheck`.

So I think depcheck should be able to find the `package.json` using `require.resolve` and scanning upwards the vast majority of the time.

I don't think it hurts to fallback on `require.resolve(name +'/package.json')` as a lot of packages do export their `package.json` files to support this.

**Comment by flying-sheep** [comment]
Yeah, so there's seemingly no correct way to do it. Packages that don't export package.json are definitely valid (official examples rarely include it), and packages without “.” exports seem to be valid (i couldn't find anything contradicting it despite all official examples including it or the shorthand).

Combine the two and there's seemingly no way to do it correctly.

**Comment by eonae** [comment]
Resolving this issue will be really nice. Yarn is nice and strict when it comes to determining **nessessary** dependencies. While depcheck is good to find unused. But right now the don't meet each other in the golden middle 😟
