### ISSUE TITLE
Fails with Top-Level Await

### ISSUE THREAD

**Issue by karlhorky** [depcheck/depcheck#671]
### Bug Description

The following files will report an unused dependency of `node-fetch`, seemingly because of top-level await not being supported:

`index.js`

```js
// 
import fetch from 'node-fetch';
await fetch('https://example.com');
```

`package.json`

```js
{
  "name": "abc",
  "type": "module",
  "main": "index.js",
  "dependencies": {
    "node-fetch": "^3.0.0"
  }
}

```

### Versions

- `node -v`: `v16.5.0`
- `npm -v`: `7.19.1`
- `depcheck --version`: `1.4.2` (latest)

### Extra info

Any extra info you want to include. Thank you for the bug report!

BONUS POINTS: If you wish to help us debug further, the `depcheck --json` option will show more information. Check [here in the README](https://github.com/depcheck/depcheck#example) for documentation on json output.

**Comment by karlhorky** [comment]
Here's the output of `depcheck --json`:

```
{"dependencies":["cheerio","node-fetch"],"devDependencies":[],"missing":{},"using":{},"invalidFiles":{"/Users/k/p/abc/index.js":"SyntaxError: Unexpected reserved word 'await'. (17:0)\n    at
      Object._raise (/Users/k/p/preflight/node_modules/@babel/parser/lib/index.js:807:17)\n    at Object.raiseWithData (/Users/k/p/preflight/node_modules/@babel/parser/lib/index.js:800:17)\n    at
      Object.raise (/Users/k/p/preflight/node_modules/@babel/parser/lib/index.js:761:17)\n    at Object.checkReservedWord (/Users/k/p/preflight/node_modules/@babel/parser/lib/index.js:12149:12)\n    at
      Object.parseIdentifierName (/Users/k/p/preflight/node_modules/@babel/parser/lib/index.js:12111:12)\n    at Object.parseIdentifier
      (/Users/k/p/preflight/node_modules/@babel/parser/lib/index.js:12078:23)\n    at Object.parseExprAtom (/Users/k/p/preflight/node_modules/@babel/parser/lib/index.js:11160:27)\n    at
      Object.parseExprAtom (/Users/k/p/preflight/node_modules/@babel/parser/lib/index.js:5216:20)\n    at Object.parseExprSubscripts
      (/Users/k/p/preflight/node_modules/@babel/parser/lib/index.js:10904:23)\n    at Object.parseUpdate (/Users/k/p/preflight/node_modules/@babel/parser/lib/index.js:10884:21)"},"invalidDirs":{}}
```

**Comment by karlhorky** [comment]
Lol I guess it was an issue with the `@babel/parser` transitive dependency, just did an `npm uninstall depcheck` and `npm install depcheck` and it worked 🙈 Closing!

**Comment by rumpl** [comment]
Hahaha, glad it all worked in the end!
