### ISSUE TITLE
False alerts on unused dependencies

### ISSUE THREAD

**Issue by blwinters** [depcheck/depcheck#673]
We have a large React Native project that uses Typescript and I installed depcheck with `npm install -g depcheck typescript`. However, when I run `depcheck` in the project root it lists pretty much all dependencies and devDependencies as unused. For example, `expo-camera` is listed as unused, but a few active files import/use it via `import { Camera } from 'expo-camera'
`.  The project uses mostly .ts and .tsx files.

I've pasted the full JSON output below as requested. Is there something else about our project config that I should check?

```
➜  pg3 git:(winters/npm-check) npx depcheck --json | json
{
  "dependencies": [
    "@okta/okta-react-native",
    "@react-native-community/datetimepicker",
    "@react-native-community/netinfo",
    "@react-native-community/progress-bar-android",
    "@react-native-community/progress-view",
    "@react-native-community/push-notification-ios",
    "@react-native-community/slider",
    "@react-native-firebase/app",
    "@react-native-firebase/crashlytics",
    "@react-native-firebase/dynamic-links",
    "@react-native-firebase/messaging",
    "@react-native-firebase/remote-config",
    "@react-native-picker/picker",
    "@reduxjs/toolkit",
    "@types/i18n-js",
    "@unimodules/core",
    "apollo-cache-inmemory",
    "apollo-cache-persist",
    "apollo-client",
    "apollo-link",
    "apollo-link-context",
    "apollo-link-error",
    "apollo-link-http",
    "apollo-link-retry",
    "expo-battery",
    "expo-brightness",
    "expo-camera",
    "expo-cellular",
    "expo-device",
    "expo-intent-launcher",
    "expo-keep-awake",
    "expo-network",
    "expo-permissions",
    "expo-web-browser",
    "fetch",
    "graphql",
    "graphql-tag",
    "i18n-js",
    "jetifier",
    "jsc-android",
    "jwt-decode",
    "libphonenumber-js",
    "moment",
    "npm-license-crawler",
    "pretty-bytes",
    "pretty-format-ast",
    "pretty-format2",
    "react-apollo",
    "react-native-aws3",
    "react-native-background-fetch",
    "react-native-carrier-info",
    "react-native-device-info",
    "react-native-device-time-format",
    "react-native-fing",
    "react-native-fs",
    "react-native-hyperlink",
    "react-native-in-app-review",
    "react-native-intercom",
    "react-native-legacy-upgrade-info",
    "react-native-network-info",
    "react-native-pdf",
    "react-native-splash-screen",
    "react-native-static-safe-area-insets",
    "react-native-typography",
    "react-native-unimodules",
    "react-native-webview",
    "react-native-zip-archive",
    "react-navigation-hooks",
    "react-navigation-tabs",
    "react-redux",
    "redux",
    "redux-devtools-extension",
    "rn-fetch-blob",
    "source-map",
    "stacktrace-js",
    "url-parse",
    "validator"
  ],
  "devDependencies": [
    "@apollo/react-testing",
    "@babel/runtime",
    "@emotion/core",
    "@testing-library/react-hooks",
    "@types/events",
    "@types/graphql",
    "@types/jest",
    "@types/moment-timezone",
    "@types/react-native-vector-icons",
    "@types/react-redux",
    "@types/react-test-renderer",
    "@types/storybook__addon-actions",
    "@types/url-parse",
    "@types/uuid",
    "@types/validator",
    "awesome-typescript-loader",
    "babel-jest",
    "babel-plugin-inline-import",
    "babel-plugin-transform-remove-console",
    "babel-preset-minify",
    "emotion-theming",
    "eslint-formatter-summary",
    "jest-circus",
    "jest-junit",
    "jest-mock-proxy",
    "jest-transform-stub",
    "metro-react-native-babel-preset",
    "node-fetch",
    "patch-package",
    "react-hooks",
    "react-native-testing-library",
    "react-test-renderer",
    "ts-jest"
  ],
  "missing": {
    "lib": [
      "/Users/benwinters/Documents/Projects/pg3/index.js",
      "/Users/benwinters/Documents/Projects/pg3/jestSetup.js",
      "/Users/benwinters/Documents/Projects/pg3/storybook/rootDecorator.tsx",
      "/Users/benwinters/Documents/Projects/pg3/storybook/native/StorybookUI.tsx"
    ],
    "src": [
      "/Users/benwinters/Documents/Projects/pg3/index.js"
    ],
    "metro-config": [
      "/Users/benwinters/Documents/Projects/pg3/metro.config.js"
    ],
    "@storybook/core-events": [
      "/Users/benwinters/Documents/Projects/pg3/storybook/native/tryToOpenStorybook.js"
    ],
    "js-yaml": [
      "/Users/benwinters/Documents/Projects/pg3/scripts/localizations/build.js",
      "/Users/benwinters/Documents/Projects/pg3/scripts/localizations/check.js",
      "/Users/benwinters/Documents/Projects/pg3/scripts/localizations/load.js",
      "/Users/benwinters/Documents/Projects/pg3/scripts/localizations/utilities.js"
    ],
    "chalk": [
      "/Users/benwinters/Documents/Projects/pg3/scripts/localizations/check.js"
    ],
    "acorn-walk": [
      "/Users/benwinters/Documents/Projects/pg3/scripts/localizations/utilities.js"
    ],
    "socket.io": [
      "/Users/benwinters/Documents/Projects/pg3/ios/DependencySource/mceSDK/Frameworks/mceSDK.xcframework/ios-i386_x86_64-simulator/mceSDK.framework/applications/user/reflow-container-bundled/bundle.js",
      "/Users/benwinters/Documents/Projects/pg3/ios/DependencySource/mceSDK/Frameworks/mceSDK.xcframework/ios-armv7_arm64/mceSDK.framework/applications/user/reflow-container-bundled/bundle.js"
    ],
    "proxy-agent": [
      "/Users/benwinters/Documents/Projects/pg3/ios/DependencySource/mceSDK/Frameworks/mceSDK.xcframework/ios-i386_x86_64-simulator/mceSDK.framework/applications/user/reflow-container-bundled/bundle.js",
      "/Users/benwinters/Documents/Projects/pg3/ios/DependencySource/mceSDK/Frameworks/mceSDK.xcframework/ios-armv7_arm64/mceSDK.framework/applications/user/reflow-container-bundled/bundle.js"
    ]
  },
  "using": {
    "@typescript-eslint/parser": [
      "/Users/benwinters/Documents/Projects/pg3/.eslintrc.js"
    ],
    "eslint-plugin-react": [
      "/Users/benwinters/Documents/Projects/pg3/.eslintrc.js"
    ],
    "eslint-plugin-react-native": [
      "/Users/benwinters/Documents/Projects/pg3/.eslintrc.js"
    ],
    "eslint-plugin-react-hooks": [
      "/Users/benwinters/Documents/Projects/pg3/.eslintrc.js"
    ],
    "eslint-plugin-prefer-arrow": [
      "/Users/benwinters/Documents/Projects/pg3/.eslintrc.js"
    ],
    "@typescript-eslint/eslint-plugin": [
      "/Users/benwinters/Documents/Projects/pg3/.eslintrc.js"
    ],
    "eslint-config-prettier": [
      "/Users/benwinters/Documents/Projects/pg3/.eslintrc.js"
    ],
    "eslint-plugin-prettier": [
      "/Users/benwinters/Documents/Projects/pg3/.eslintrc.js"
    ],
    "eslint": [
      "/Users/benwinters/Documents/Projects/pg3/.eslintrc.js",
      "/Users/benwinters/Documents/Projects/pg3/package.json"
    ],
    "prettier": [
      "/Users/benwinters/Documents/Projects/pg3/.eslintrc.js",
      "/Users/benwinters/Documents/Projects/pg3/package.json"
    ],
    "reactotron-react-native": [
      "/Users/benwinters/Documents/Projects/pg3/ReactotronConfig.js"
    ],
    "react": [
      "/Users/benwinters/Documents/Projects/pg3/ReactotronConfig.js",
      "/Users/benwinters/Documents/Projects/pg3/index.d.tsx",
      "/Users/benwinters/Documents/Projects/pg3/index.js",
      "/Users/benwinters/Documents/Projects/pg3/jestSetup.js",
      "/Users/benwinters/Documents/Projects/pg3/package.json",
      "/Users/benwinters/Documents/Projects/pg3/package.json",
      "/Users/benwinters/Documents/Projects/pg3/storybook/rootDecorator.tsx",
      "/Users/benwinters/Documents/Projects/pg3/storybook/web/.babelrc",
      "/Users/benwinters/Documents/Projects/pg3/storybook/web/addons.js",
      "/Users/benwinters/Documents/Projects/pg3/storybook/web/config.jsx",
      "/Users/benwinters/Documents/Projects/pg3/storybook/native/StorybookUI.tsx",
      "/Users/benwinters/Documents/Projects/pg3/storybook/native/addons.js",
      "/Users/benwinters/Documents/Projects/pg3/storybook/native/rn-addons.js",
      "/Users/benwinters/Documents/Projects/pg3/__mocks__/nativeModules.js"
    ],
    "react-native": [
      "/Users/benwinters/Documents/Projects/pg3/ReactotronConfig.js",
      "/Users/benwinters/Documents/Projects/pg3/index.d.tsx",
      "/Users/benwinters/Documents/Projects/pg3/index.js",
      "/Users/benwinters/Documents/Projects/pg3/jestSetup.js",
      "/Users/benwinters/Documents/Projects/pg3/metro.config.js",
      "/Users/benwinters/Documents/Projects/pg3/package.json",
      "/Users/benwinters/Documents/Projects/pg3/package.json",
      "/Users/benwinters/Documents/Projects/pg3/storybook/rootDecorator.tsx",
      "/Users/benwinters/Documents/Projects/pg3/storybook/web/config.jsx",
      "/Users/benwinters/Documents/Projects/pg3/storybook/native/StorybookUI.tsx",
      "/Users/benwinters/Documents/Projects/pg3/storybook/native/index.js",
      "/Users/benwinters/Documents/Projects/pg3/storybook/native/rn-addons.js",
      "/Users/benwinters/Documents/Projects/pg3/__mocks__/nativeModules.js"
    ],
    "react-native-svg": [
      "/Users/benwinters/Documents/Projects/pg3/index.d.tsx",
      "/Users/benwinters/Documents/Projects/pg3/metro.config.js"
    ],
    "@types/react-native": [
      "/Users/benwinters/Documents/Projects/pg3/index.d.tsx",
      "/Users/benwinters/Documents/Projects/pg3/storybook/native/StorybookUI.tsx"
    ],
    "react-native-gesture-handler": [
      "/Users/benwinters/Documents/Projects/pg3/index.js",
      "/Users/benwinters/Documents/Projects/pg3/jestSetup.js",
      "/Users/benwinters/Documents/Projects/pg3/storybook/native/StorybookUI.tsx"
    ],
    "lib": [
      "/Users/benwinters/Documents/Projects/pg3/index.js",
      "/Users/benwinters/Documents/Projects/pg3/jestSetup.js",
      "/Users/benwinters/Documents/Projects/pg3/storybook/rootDecorator.tsx",
      "/Users/benwinters/Documents/Projects/pg3/storybook/native/StorybookUI.tsx"
    ],
    "src": [
      "/Users/benwinters/Documents/Projects/pg3/index.js"
    ],
    "jest-styled-components": [
      "/Users/benwinters/Documents/Projects/pg3/jestSetup.js"
    ],
    "@react-native-community/async-storage": [
      "/Users/benwinters/Documents/Projects/pg3/jestSetup.js"
    ],
    "expo-localization": [
      "/Users/benwinters/Documents/Projects/pg3/jestSetup.js"
    ],
    "moment-timezone": [
      "/Users/benwinters/Documents/Projects/pg3/jestSetup.js"
    ],
    "react-native-reanimated": [
      "/Users/benwinters/Documents/Projects/pg3/jestSetup.js"
    ],
    "jest-fetch-mock": [
      "/Users/benwinters/Documents/Projects/pg3/jestSetup.js"
    ],
    "styled-components": [
      "/Users/benwinters/Documents/Projects/pg3/jestSetup.js",
      "/Users/benwinters/Documents/Projects/pg3/storybook/web/config.jsx",
      "/Users/benwinters/Documents/Projects/pg3/storybook/native/StorybookUI.tsx"
    ],
    "metro-config": [
      "/Users/benwinters/Documents/Projects/pg3/metro.config.js"
    ],
    "react-native-svg-transformer": [
      "/Users/benwinters/Documents/Projects/pg3/metro.config.js"
    ],
    "@storybook/react": [
      "/Users/benwinters/Documents/Projects/pg3/package.json",
      "/Users/benwinters/Documents/Projects/pg3/storybook/web/config.jsx"
    ],
    "@storybook/react-native-server": [
      "/Users/benwinters/Documents/Projects/pg3/package.json"
    ],
    "apollo": [
      "/Users/benwinters/Documents/Projects/pg3/package.json"
    ],
    "jest": [
      "/Users/benwinters/Documents/Projects/pg3/package.json"
    ],
    "lerna": [
      "/Users/benwinters/Documents/Projects/pg3/package.json"
    ],
    "react-native-storybook-loader": [
      "/Users/benwinters/Documents/Projects/pg3/package.json"
    ],
    "typescript": [
      "/Users/benwinters/Documents/Projects/pg3/package.json"
    ],
    "@babel/core": [
      "/Users/benwinters/Documents/Projects/pg3/package.json",
      "/Users/benwinters/Documents/Projects/pg3/storybook/web/config.jsx"
    ],
    "babel-loader": [
      "/Users/benwinters/Documents/Projects/pg3/package.json",
      "/Users/benwinters/Documents/Projects/pg3/storybook/web/config.jsx"
    ],
    "react-dom": [
      "/Users/benwinters/Documents/Projects/pg3/package.json",
      "/Users/benwinters/Documents/Projects/pg3/storybook/web/.babelrc",
      "/Users/benwinters/Documents/Projects/pg3/storybook/web/config.jsx",
      "/Users/benwinters/Documents/Projects/pg3/storybook/native/StorybookUI.tsx"
    ],
    "@types/react": [
      "/Users/benwinters/Documents/Projects/pg3/storybook/rootDecorator.tsx",
      "/Users/benwinters/Documents/Projects/pg3/storybook/native/StorybookUI.tsx"
    ],
    "react-native-paper": [
      "/Users/benwinters/Documents/Projects/pg3/storybook/rootDecorator.tsx"
    ],
    "react-native-vector-icons": [
      "/Users/benwinters/Documents/Projects/pg3/storybook/rootDecorator.tsx"
    ],
    "babel-plugin-macros": [
      "/Users/benwinters/Documents/Projects/pg3/storybook/web/.babelrc"
    ],
    "babel-plugin-react-native-web": [
      "/Users/benwinters/Documents/Projects/pg3/storybook/web/.babelrc"
    ],
    "react-native-web": [
      "/Users/benwinters/Documents/Projects/pg3/storybook/web/.babelrc"
    ],
    "@storybook/addon-actions": [
      "/Users/benwinters/Documents/Projects/pg3/storybook/web/addons.js",
      "/Users/benwinters/Documents/Projects/pg3/storybook/native/addons.js",
      "/Users/benwinters/Documents/Projects/pg3/storybook/native/rn-addons.js"
    ],
    "@storybook/addon-knobs": [
      "/Users/benwinters/Documents/Projects/pg3/storybook/web/addons.js",
      "/Users/benwinters/Documents/Projects/pg3/storybook/web/config.jsx",
      "/Users/benwinters/Documents/Projects/pg3/storybook/native/StorybookUI.tsx",
      "/Users/benwinters/Documents/Projects/pg3/storybook/native/addons.js",
      "/Users/benwinters/Documents/Projects/pg3/storybook/native/rn-addons.js"
    ],
    "@storybook/addon-viewport": [
      "/Users/benwinters/Documents/Projects/pg3/storybook/web/addons.js"
    ],
    "@types/styled-components": [
      "/Users/benwinters/Documents/Projects/pg3/storybook/native/StorybookUI.tsx"
    ],
    "react-navigation-stack": [
      "/Users/benwinters/Documents/Projects/pg3/storybook/native/StorybookUI.tsx"
    ],
    "@storybook/react-native": [
      "/Users/benwinters/Documents/Projects/pg3/storybook/native/StorybookUI.tsx"
    ],
    "@types/storybook__react-native": [
      "/Users/benwinters/Documents/Projects/pg3/storybook/native/StorybookUI.tsx"
    ],
    "@types/storybook__addon-knobs": [
      "/Users/benwinters/Documents/Projects/pg3/storybook/native/StorybookUI.tsx"
    ],
    "@react-native-community/masked-view": [
      "/Users/benwinters/Documents/Projects/pg3/storybook/native/StorybookUI.tsx"
    ],
    "react-native-safe-area-context": [
      "/Users/benwinters/Documents/Projects/pg3/storybook/native/StorybookUI.tsx"
    ],
    "react-native-screens": [
      "/Users/benwinters/Documents/Projects/pg3/storybook/native/StorybookUI.tsx"
    ],
    "react-navigation": [
      "/Users/benwinters/Documents/Projects/pg3/storybook/native/StorybookUI.tsx"
    ],
    "react-native-dev-menu": [
      "/Users/benwinters/Documents/Projects/pg3/storybook/native/index.js"
    ],
    "@storybook/addon-ondevice-actions": [
      "/Users/benwinters/Documents/Projects/pg3/storybook/native/rn-addons.js"
    ],
    "@storybook/addon-ondevice-knobs": [
      "/Users/benwinters/Documents/Projects/pg3/storybook/native/rn-addons.js"
    ],
    "@storybook/addons": [
      "/Users/benwinters/Documents/Projects/pg3/storybook/native/tryToOpenStorybook.js"
    ],
    "@storybook/core-events": [
      "/Users/benwinters/Documents/Projects/pg3/storybook/native/tryToOpenStorybook.js"
    ],
    "js-yaml": [
      "/Users/benwinters/Documents/Projects/pg3/scripts/localizations/build.js",
      "/Users/benwinters/Documents/Projects/pg3/scripts/localizations/check.js",
      "/Users/benwinters/Documents/Projects/pg3/scripts/localizations/load.js",
      "/Users/benwinters/Documents/Projects/pg3/scripts/localizations/utilities.js"
    ],
    "chalk": [
      "/Users/benwinters/Documents/Projects/pg3/scripts/localizations/check.js"
    ],
    "cli-table": [
      "/Users/benwinters/Documents/Projects/pg3/scripts/localizations/check.js"
    ],
    "acorn-loose": [
      "/Users/benwinters/Documents/Projects/pg3/scripts/localizations/utilities.js"
    ],
    "acorn-walk": [
      "/Users/benwinters/Documents/Projects/pg3/scripts/localizations/utilities.js"
    ],
    "socket.io": [
      "/Users/benwinters/Documents/Projects/pg3/ios/DependencySource/mceSDK/Frameworks/mceSDK.xcframework/ios-i386_x86_64-simulator/mceSDK.framework/applications/user/reflow-container-bundled/bundle.js",
      "/Users/benwinters/Documents/Projects/pg3/ios/DependencySource/mceSDK/Frameworks/mceSDK.xcframework/ios-armv7_arm64/mceSDK.framework/applications/user/reflow-container-bundled/bundle.js"
    ],
    "proxy-agent": [
      "/Users/benwinters/Documents/Projects/pg3/ios/DependencySource/mceSDK/Frameworks/mceSDK.xcframework/ios-i386_x86_64-simulator/mceSDK.framework/applications/user/reflow-container-bundled/bundle.js",
      "/Users/benwinters/Documents/Projects/pg3/ios/DependencySource/mceSDK/Frameworks/mceSDK.xcframework/ios-armv7_arm64/mceSDK.framework/applications/user/reflow-container-bundled/bundle.js"
    ],
    "detox": [
      "/Users/benwinters/Documents/Projects/pg3/e2e/environment.js"
    ]
  },
  "invalidFiles": {
    "/Users/benwinters/Documents/Projects/pg3/ios/SNCRDependencies/PhotoPuzzle.framework/puzzle-game/game/js/ctl_utils.js": "SyntaxError: Identifier 'shuffle' has already been declared. (528:9)\n    at Object._raise (/Users/benwinters/.nodenv/versions/12.2.0/lib/node_modules/depcheck/node_modules/@babel/parser/lib/index.js:808:17)\n    at Object.raiseWithData (/Users/benwinters/.nodenv/versions/12.2.0/lib/node_modules/depcheck/node_modules/@babel/parser/lib/index.js:801:17)\n    at Object.raise (/Users/benwinters/.nodenv/versions/12.2.0/lib/node_modules/depcheck/node_modules/@babel/parser/lib/index.js:762:17)\n    at FlowScopeHandler.checkRedeclarationInScope (/Users/benwinters/.nodenv/versions/12.2.0/lib/node_modules/depcheck/node_modules/@babel/parser/lib/index.js:1437:12)\n    at FlowScopeHandler.declareName (/Users/benwinters/.nodenv/versions/12.2.0/lib/node_modules/depcheck/node_modules/@babel/parser/lib/index.js:1403:12)\n    at FlowScopeHandler.declareName (/Users/benwinters/.nodenv/versions/12.2.0/lib/node_modules/depcheck/node_modules/@babel/parser/lib/index.js:1519:11)\n    at Object.registerFunctionStatementId (/Users/benwinters/.nodenv/versions/12.2.0/lib/node_modules/depcheck/node_modules/@babel/parser/lib/index.js:13577:16)\n    at Object.parseFunction (/Users/benwinters/.nodenv/versions/12.2.0/lib/node_modules/depcheck/node_modules/@babel/parser/lib/index.js:13557:12)\n    at Object.parseFunctionStatement (/Users/benwinters/.nodenv/versions/12.2.0/lib/node_modules/depcheck/node_modules/@babel/parser/lib/index.js:13186:17)\n    at Object.parseStatementContent (/Users/benwinters/.nodenv/versions/12.2.0/lib/node_modules/depcheck/node_modules/@babel/parser/lib/index.js:12867:21)"
  },
  "invalidDirs": {}
}
```

**Comment by Wyctus** [comment]
Same here in a large RN project.

**Comment by josemlira** [comment]
Hi! Do we have any updates on this? I'm also having this issue in a RN project.

**Comment by anatooly** [comment]
As for me actual too
npx depcheck show all dependencies is unused. Project mixed ts+js

**Comment by hixus** [comment]
Same here. For  backend project worked fine but rn all are marked as unused. Both typescript projects.

**Comment by rumpl** [comment]
The output of “depcheck —json” would really help

**Comment by aitorct** [comment]
Same issue here in a React Native project. This should be re-opened.

**Comment by aitorct** [comment]
Same issue here in a React Native project. This should be re-opened.

@rumpl The output of `depcheck --json` was added in the original post by @blwinters.

**Comment by jheurtin** [comment]
Same issue here, can we re-open it ? 🙏🏻
