### ISSUE TITLE
Depcheck fails on express, socketio, mongodb

### ISSUE THREAD

**Issue by theahura** [depcheck/depcheck#693]
### Bug Description

I have an index.ts file that imports a set of libraries. These are considered missing by depcheck. See code snippets below.
Error is:
```
Unused dependencies
* @aws-sdk/client-secrets-manager
* express
* mongodb
* socket.io
Unused devDependencies
* @types/express
```

### Code snippets

Where the dependency is used:

```
import express from 'express';                    
import * as http from 'http';                                                                        
import { Server } from 'socket.io';                                                                  
import { MongoClient } from 'mongodb';                                                               
import {                                          
  SecretsManagerClient,                                                                                                                                                                                    
  GetSecretValueCommand,                          
} from '@aws-sdk/client-secrets-manager'; 
```

Where the dependency is listed in package.json:

```
  "dependencies": {
    "@aws-sdk/client-secrets-manager": "^3.43.0",
    "@types/node": "^16.11.12",
    "express": "^4.17.1",
    "mongodb": "^4.2.1",
    "socket.io": "^4.4.0"
  },
  "devDependencies": {
    "@types/express": "^4.17.13",
    "ts-node": "^10.4.0",
    "typescript": "^4.5.2"
  }
```

### Versions

- `node -v`: 14.18.1
- `npm -v`: 6.14.15
- `depcheck --version`: 1.4.2

### Extra info

Any extra info you want to include. Thank you for the bug report!
depcheck --json
```
{"dependencies":["@aws-sdk/client-secrets-manager","express","mongodb","socket.io"],"devDependencies":["@types/express"],"missing":{},"using":{"ts-node":["/home/soot/code/soot/messagebus/package.json"],"@types/node":["/home/soot/code/soot/messagebus/package.json"],"typescript":["/home/soot/code/soot/messagebus/package.json"]},"invalidFiles":{"/home/soot/code/soot/messagebus/src/index.ts":"TypeError: p is not iterable\n    at /home/soot/.nvm/versions/node/v14.18.1/lib/node_modules/depcheck/node_modules/@babel/parser/lib/index.js:10658:43\n    at Array.some (<anonymous>)\n    at hasPlugin (/home/soot/.nvm/versions/node/v14.18.1/lib/node_modules/depcheck/node_modules/@babel/parser/lib/index.js:10654:18)\n    at validatePlugins (/home/soot/.nvm/versions/node/v14.18.1/lib/node_modules/depcheck/node_modules/@babel/parser/lib/index.js:10693:7)\n    at getParser (/home/soot/.nvm/versions/node/v14.18.1/lib/node_modules/depcheck/node_modules/@babel/parser/lib/index.js:15283:5)\n    at parse (/home/soot/.nvm/versions/node/v14.18.1/lib/node_modules/depcheck/node_modules/@babel/parser/lib/index.js:15254:12)\n    at parseTypescript (/home/soot/.nvm/versions/node/v14.18.1/lib/node_modules/depcheck/dist/parser/typescript.js:17:28)\n    at async getDependencies (/home/soot/.nvm/versions/node/v14.18.1/lib/node_modules/depcheck/dist/check.js:71:18)\n    at async Promise.all (index 172)\n    at async cli (/home/soot/.nvm/versions/node/v14.18.1/lib/node_modules/depcheck/dist/cli.js:93:28)"},"invalidDirs":{}}
```

**Comment by kpala** [comment]
Based on the provided `depcheck --json` output, you are getting the same error as reported in https://github.com/depcheck/depcheck/issues/688.
