### ISSUE TITLE
Depcheck errors without "--parsers" flag

### ISSUE THREAD

**Issue by supalarry** [depcheck/depcheck#735]
### Bug Description

If I do not add `--parsers` flag, then I get syntax errors raised by the babel parser.
However, if I add ANYTHING in the `--parsers` flag, the syntax errors raised by babel are gone.

### Not working example
```
pnpm depcheck --json
...
...
"invalidFiles": {
        "/first/file.ts": "SyntaxError: Unexpected token, expected \"}\" (137:26)\n    at Object._raise (/Users/lauris/src/on-deck/node_modules/.pnpm/@babel+parser@7.16.4/node_modules/@babel/parser/lib/index.js:541:17)\n    at Object.raiseWithData (/Users/lauris/src/on-deck/node_modules/.pnpm/@babel+parser@7.16.4/node_modules/@babel/parser/lib/index.js:534:17)\n    at Object.raise (/Users/lauris/src/on-deck/node_modules/.pnpm/@babel+parser@7.16.4/node_modules/@babel/parser/lib/index.js:495:17)\n    at Object.unexpected (/Users/lauris/src/on-deck/node_modules/.pnpm/@babel+parser@7.16.4/node_modules/@babel/parser/lib/index.js:3580:16)\n    at Object.expect (/Users/lauris/src/on-deck/node_modules/.pnpm/@babel+parser@7.16.4/node_modules/@babel/parser/lib/index.js:3554:28)\n    at Object.jsxParseExpressionContainer (/Users/lauris/src/on-deck/node_modules/.pnpm/@babel+parser@7.16.4/node_modules/@babel/parser/lib/index.js:7331:10)\n    at Object.jsxParseElementAt (/Users/lauris/src/on-deck/node_modules/.pnpm/@babel+parser@7.16.4/node_modules/@babel/parser/lib/index.js:7422:36)\n    at Object.jsxParseElement (/Users/lauris/src/on-deck/node_modules/.pnpm/@babel+parser@7.16.4/node_modules/@babel/parser/lib/index.js:7465:17)\n    at Object.parseExprAtom (/Users/lauris/src/on-deck/node_modules/.pnpm/@babel+parser@7.16.4/node_modules/@babel/parser/lib/index.js:7472:19)\n    at Object.parseExprSubscripts (/Users/lauris/src/on-deck/node_modules/.pnpm/@babel+parser@7.16.4/node_modules/@babel/parser/lib/index.js:11584:23)",
        "/second/file.ts": "SyntaxError: Unexpected token (13:23)\n    at Object._raise (/Users/lauris/src/on-deck/node_modules/.pnpm/@babel+parser@7.16.4/node_modules/@babel/parser/lib/index.js:541:17)\n    at Object.raiseWithData (/Users/lauris/src/on-deck/node_modules/.pnpm/@babel+parser@7.16.4/node_modules/@babel/parser/lib/index.js:534:17)\n    at Object.raise (/Users/lauris/src/on-deck/node_modules/.pnpm/@babel+parser@7.16.4/node_modules/@babel/parser/lib/index.js:495:17)\n    at Object.unexpected (/Users/lauris/src/on-deck/node_modules/.pnpm/@babel+parser@7.16.4/node_modules/@babel/parser/lib/index.js:3580:16)\n    at Object.jsxParseIdentifier (/Users/lauris/src/on-deck/node_modules/.pnpm/@babel+parser@7.16.4/node_modules/@babel/parser/lib/index.js:7250:12)\n    at Object.jsxParseNamespacedName (/Users/lauris/src/on-deck/node_modules/.pnpm/@babel+parser@7.16.4/node_modules/@babel/parser/lib/index.js:7260:23)\n    at Object.jsxParseElementName (/Users/lauris/src/on-deck/node_modules/.pnpm/@babel+parser@7.16.4/node_modules/@babel/parser/lib/index.js:7271:21)\n    at Object.jsxParseOpeningElementAt (/Users/lauris/src/on-deck/node_modules/.pnpm/@babel+parser@7.16.4/node_modules/@babel/parser/lib/index.js:7358:22)\n    at Object.jsxParseElementAt (/Users/lauris/src/on-deck/node_modules/.pnpm/@babel+parser@7.16.4/node_modules/@babel/parser/lib/index.js:7391:33)\n    at Object.jsxParseElement (/Users/lauris/src/on-deck/node_modules/.pnpm/@babel+parser@7.16.4/node_modules/@babel/parser/lib/index.js:7465:17)",
        "/third/file.ts": "SyntaxError: Unexpected token, expected \"}\" (23:11)\n    at Object._raise (/Users/lauris/src/on-deck/node_modules/.pnpm/@babel+parser@7.16.4/node_modules/@babel/parser/lib/index.js:541:17)\n    at Object.raiseWithData (/Users/lauris/src/on-deck/node_modules/.pnpm/@babel+parser@7.16.4/node_modules/@babel/parser/lib/index.js:534:17)\n    at Object.raise (/Users/lauris/src/on-deck/node_modules/.pnpm/@babel+parser@7.16.4/node_modules/@babel/parser/lib/index.js:495:17)\n    at Object.unexpected (/Users/lauris/src/on-deck/node_modules/.pnpm/@babel+parser@7.16.4/node_modules/@babel/parser/lib/index.js:3580:16)\n    at Object.expect (/Users/lauris/src/on-deck/node_modules/.pnpm/@babel+parser@7.16.4/node_modules/@babel/parser/lib/index.js:3554:28)\n    at Object.jsxParseExpressionContainer (/Users/lauris/src/on-deck/node_modules/.pnpm/@babel+parser@7.16.4/node_modules/@babel/parser/lib/index.js:7331:10)\n    at Object.jsxParseElementAt (/Users/lauris/src/on-deck/node_modules/.pnpm/@babel+parser@7.16.4/node_modules/@babel/parser/lib/index.js:7422:36)\n    at Object.jsxParseElement (/Users/lauris/src/on-deck/node_modules/.pnpm/@babel+parser@7.16.4/node_modules/@babel/parser/lib/index.js:7465:17)\n    at Object.parseExprAtom (/Users/lauris/src/on-deck/node_modules/.pnpm/@babel+parser@7.16.4/node_modules/@babel/parser/lib/index.js:7472:19)\n    at Object.parseExprSubscripts (/Users/lauris/src/on-deck/node_modules/.pnpm/@babel+parser@7.16.4/node_modules/@babel/parser/lib/index.js:11584:23)",
        "/fourth/file.ts": "SyntaxError: Unexpected token (20:2)\n    at Object._raise (/Users/lauris/src/on-deck/node_modules/.pnpm/@babel+parser@7.16.4/node_modules/@babel/parser/lib/index.js:541:17)\n    at Object.raiseWithData (/Users/lauris/src/on-deck/node_modules/.pnpm/@babel+parser@7.16.4/node_modules/@babel/parser/lib/index.js:534:17)\n    at Object.raise (/Users/lauris/src/on-deck/node_modules/.pnpm/@babel+parser@7.16.4/node_modules/@babel/parser/lib/index.js:495:17)\n    at Object.unexpected (/Users/lauris/src/on-deck/node_modules/.pnpm/@babel+parser@7.16.4/node_modules/@babel/parser/lib/index.js:3580:16)\n    at Object.parseExprAtom (/Users/lauris/src/on-deck/node_modules/.pnpm/@babel+parser@7.16.4/node_modules/@babel/parser/lib/index.js:12026:22)\n    at Object.parseExprAtom (/Users/lauris/src/on-deck/node_modules/.pnpm/@babel+parser@7.16.4/node_modules/@babel/parser/lib/index.js:7477:20)\n    at Object.parseExprSubscripts (/Users/lauris/src/on-deck/node_modules/.pnpm/@babel+parser@7.16.4/node_modules/@babel/parser/lib/index.js:11584:23)\n    at Object.parseUpdate (/Users/lauris/src/on-deck/node_modules/.pnpm/@babel+parser@7.16.4/node_modules/@babel/parser/lib/index.js:11564:21)\n    at Object.parseMaybeUnary (/Users/lauris/src/on-deck/node_modules/.pnpm/@babel+parser@7.16.4/node_modules/@babel/parser/lib/index.js:11539:23)\n    at Object.parseMaybeUnary (/Users/lauris/src/on-deck/node_modules/.pnpm/@babel+parser@7.16.4/node_modules/@babel/parser/lib/index.js:9918:20)",
        "/fifth/file.ts": "SyntaxError: Unexpected token, expected \"}\" (24:9)\n    at Object._raise (/Users/lauris/src/on-deck/node_modules/.pnpm/@babel+parser@7.16.4/node_modules/@babel/parser/lib/index.js:541:17)\n    at Object.raiseWithData (/Users/lauris/src/on-deck/node_modules/.pnpm/@babel+parser@7.16.4/node_modules/@babel/parser/lib/index.js:534:17)\n    at Object.raise (/Users/lauris/src/on-deck/node_modules/.pnpm/@babel+parser@7.16.4/node_modules/@babel/parser/lib/index.js:495:17)\n    at Object.unexpected (/Users/lauris/src/on-deck/node_modules/.pnpm/@babel+parser@7.16.4/node_modules/@babel/parser/lib/index.js:3580:16)\n    at Object.expect (/Users/lauris/src/on-deck/node_modules/.pnpm/@babel+parser@7.16.4/node_modules/@babel/parser/lib/index.js:3554:28)\n    at Object.jsxParseExpressionContainer (/Users/lauris/src/on-deck/node_modules/.pnpm/@babel+parser@7.16.4/node_modules/@babel/parser/lib/index.js:7331:10)\n    at Object.jsxParseElementAt (/Users/lauris/src/on-deck/node_modules/.pnpm/@babel+parser@7.16.4/node_modules/@babel/parser/lib/index.js:7422:36)\n    at Object.jsxParseElement (/Users/lauris/src/on-deck/node_modules/.pnpm/@babel+parser@7.16.4/node_modules/@babel/parser/lib/index.js:7465:17)\n    at Object.parseExprAtom (/Users/lauris/src/on-deck/node_modules/.pnpm/@babel+parser@7.16.4/node_modules/@babel/parser/lib/index.js:7472:19)\n    at Object.parseExprSubscripts (/Users/lauris/src/on-deck/node_modules/.pnpm/@babel+parser@7.16.4/node_modules/@babel/parser/lib/index.js:11584:23)"
    },
    "invalidDirs": {}
}
```

### Working example

```
pnpm depcheck --json --parsers="hello:world"
...
...
"invalidFiles":{},
"invalidDirs":{}
}
```

When I said adding anything in the parsers flag I meant literally anything. I added actually ran  `--parsers` with the value of `"hello:world"`.

### Versions

- `node -v`: v16.15.1
- `npm -v`: I do not use npm. I use pnpm at 7.1.9
- `depcheck --version`: 1.4.3

**Comment by kaboing** [comment]
Same for me

```
    "invalidFiles": {
        "...\\lib\\file1.ts": "SyntaxError: Unexpected token, expected \"}\" (73:79)\n    at Object._raise (C:\\ProgramData\\nvm\\v16.17.1\\node_modules\\depcheck\\node_modules\\@babel\\parser\\lib\\index.js:541:17)\n    at Object.raiseWithData (C:\\ProgramData\\nvm\\v16.17.1\\node_modules\\depcheck\\node_modules\\@babel\\parser\\lib\\index.js:534:17)\n    at Object.raise (C:\\ProgramData\\nvm\\v16.17.1\\node_modules\\depcheck\\node_modules\\@babel\\parser\\lib\\index.js:495:17)\n    at Object.unexpected (C:\\ProgramData\\nvm\\v16.17.1\\node_modules\\depcheck\\node_modules\\@babel\\parser\\lib\\index.js:3580:16)\n    at Object.expect (C:\\ProgramData\\nvm\\v16.17.1\\node_modules\\depcheck\\node_modules\\@babel\\parser\\lib\\index.js:3554:28)\n    at Object.jsxParseSpreadChild (C:\\ProgramData\\nvm\\v16.17.1\\node_modules\\depcheck\\node_modules\\@babel\\parser\\lib\\index.js:7319:10)\n    at Object.jsxParseElementAt (C:\\ProgramData\\nvm\\v16.17.1\\node_modules\\depcheck\\node_modules\\@babel\\parser\\lib\\index.js:7420:36)\n    at Object.jsxParseElement (C:\\ProgramData\\nvm\\v16.17.1\\node_modules\\depcheck\\node_modules\\@babel\\parser\\lib\\index.js:7465:17)\n    at Object.parseExprAtom (C:\\ProgramData\\nvm\\v16.17.1\\node_modules\\depcheck\\node_modules\\@babel\\parser\\lib\\index.js:7472:19)\n    at Object.parseExprSubscripts (C:\\ProgramData\\nvm\\v16.17.1\\node_modules\\depcheck\\node_modules\\@babel\\parser\\lib\\index.js:11584:23)",
        "...\\controllers\\file2.ts": "SyntaxError: Unexpected token, expected \"}\" (267:6)\n    at Object._raise (C:\\ProgramData\\nvm\\v16.17.1\\node_modules\\depcheck\\node_modules\\@babel\\parser\\lib\\index.js:541:17)\n    at Object.raiseWithData (C:\\ProgramData\\nvm\\v16.17.1\\node_modules\\depcheck\\node_modules\\@babel\\parser\\lib\\index.js:534:17)\n    at Object.raise (C:\\ProgramData\\nvm\\v16.17.1\\node_modules\\depcheck\\node_modules\\@babel\\parser\\lib\\index.js:495:17)\n    at Object.unexpected (C:\\ProgramData\\nvm\\v16.17.1\\node_modules\\depcheck\\node_modules\\@babel\\parser\\lib\\index.js:3580:16)\n    at Object.expect (C:\\ProgramData\\nvm\\v16.17.1\\node_modules\\depcheck\\node_modules\\@babel\\parser\\lib\\index.js:3554:28)\n    at Object.jsxParseSpreadChild (C:\\ProgramData\\nvm\\v16.17.1\\node_modules\\depcheck\\node_modules\\@babel\\parser\\lib\\index.js:7319:10)\n    at Object.jsxParseElementAt (C:\\ProgramData\\nvm\\v16.17.1\\node_modules\\depcheck\\node_modules\\@babel\\parser\\lib\\index.js:7420:36)\n    at Object.jsxParseElement (C:\\ProgramData\\nvm\\v16.17.1\\node_modules\\depcheck\\node_modules\\\\ProgramData\\nvm\\v16.17.1\\node_modules\\depcheck\\node_modules\\@babel\\parser\\lib\\index.js:534:17)\n    at Object.raise (C:\\ProgramData\\nvm\\v16.17.1\\node_modules\\depcheck\\node_modules\\@babel\\parser\\lib\\index.js:495:17)\n    at Object.unexpected (C:\\ProgramData\\nvm\\v16.17.1\\node_modules\\depcheck\\node_modules\\@babel\\parser\\lib\\index.js:3580:16)\n    at Object.expect (C:\\ProgramData\\nvm\\v16.17.1\\node_modules\\depcheck\\node_modules\\@babel\\parser\\lib\\index.js:3554:28)\n    at Object.jsxParseSpreadChild (C:\\ProgramData\\nvm\\v16.17.1\\node_modules\\depcheck\\node_modules\\@babel\\parser\\lib\\index.js:7319:10)\n    at Object.jsxParseElementAt (C:\\ProgramData\\nvm\\v16.17.1\\node_modules\\depcheck\\node_modules\\@babel\\parser\\lib\\index.js:7420:36)\n    at Object.jsxParseElement (C:\\ProgramData\\nvm\\v16.17.1\\node_modules\\depcheck\\node_modules\\@babel\\parser\\lib\\index.js:7465:17)\n    at Object.parseExprAtom (C:\\ProgramData\\nvm\\v16.17.1\\node_modules\\depcheck\\node_modules\\@babel\\parser\\lib\\index.js:7472:19)\n    at Object.parseExprSubscripts (C:\\ProgramData\\nvm\\v16.17.1\\node_modules\\depcheck\\node_modules\\@babel\\parser\\lib\\index.js:11584:23)",
        "...\\src\\controllers\\file3.ts": "SyntaxError: Unexpected token, expected \"}\" (165:6)\n    at Object._raise (C:\\ProgramData\\nvm\\v16.17.1\\node_modules\\depcheck\\node_modules\\@babel\\parser\\lib\\index.js:541:17)\n    at Object.raiseWithData (C:\\ProgramData\\nvm\\v16.17.1\\node_modules\\depcheck\\node_modules\\@babel\\parser\\lib\\index.js:534:17)\n    at Object.raise (C:\\ProgramData\\nvm\\v16.17.1\\node_modules\\depcheck\\node_modules\\@babel\\parser\\lib\\index.js:495:17)\n    at Object.unexpected (C:\\ProgramData\\nvm\\v16.17.1\\node_modules\\depcheck\\node_modules\\@babel\\parser\\lib\\index.js:3580:16)\n    at Object.expect (C:\\ProgramData\\nvm\\v16.17.1\\node_modules\\depcheck\\node_modules\\@babel\\parser\\lib\\index.js:3554:28)\n    at Object.jsxParseSpreadChild (C:\\ProgramData\\nvm\\v16.17.1\\node_modules\\depcheck\\node_modules\\@babel\\parser\\lib\\index.js:7319:10)\n    at Object.jsxParseElementAt (C:\\ProgramData\\nvm\\v16.17.1\\node_modules\\depcheck\\node_modules\\@babel\\parser\\lib\\index.js:7420:36)\n    at Object.jsxParseElement (C:\\ProgramData\\nvm\\v16.17.1\\node_modules\\depcheck\\node_modules\\@babel\\parser\\lib\\index.js:7465:17)\n    at Object.parseExprAtom (C:\\ProgramData\\nvm\\v16.17.1\\node_modules\\depcheck\\node_modules\\@babel\\parser\\lib\\index.js:7472:19)\n    at Object.parseExprSubscripts (C:\\ProgramData\\nvm\\v16.17.1\\node_modules\\depcheck\\node_modules\\@babel\\parser\\lib\\index.js:11584:23)"
    },

```
### Versions
* node -v: 16.17.1
* depcheck --version: 1.4.3

**Comment by jitsedesmet** [comment]
I had the same issue. For me, the issue was solved when disabling the `jsx` option in https://github.com/depcheck/depcheck/blob/main/src/parser/typescript.js#L13. Maybe this should be an option somehow? I use the `<>` cast syntax and fear that this would clash with jsx somehow, but this is only an assumption.
