### ISSUE TITLE
Cannot load metadata from ESM package

### ISSUE THREAD

**Issue by timdp** [depcheck/depcheck#753]
### Bug Description

`utils.loadModuleData()` is defeated b yESM packages.

### Code snippets

```
{
  "name": "depcheck-test",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "test": "depcheck .",
    "foo": "miniflare baz"
  },
  "dependencies": {
    "depcheck": "^1.4.3",
    "miniflare": "^2.9.0"
  }
}
```

This crashes the [`require.resolve('.../package.json')` call](https://github.com/depcheck/depcheck/blob/5132d5ef71feb039d5fec0615f2dd0a04f6ff285/src/utils/index.js#L24) in `loadModuleData` with:

```
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './package.json' is not defined by "exports" in /Users/timdp/Code/depcheck-test/node_modules/miniflare/package.json
    at new NodeError (node:internal/errors:393:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:340:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:619:3)
    at resolveExports (node:internal/modules/cjs/loader:492:36)
    at Module._findPath (node:internal/modules/cjs/loader:532:31)
    at Module._resolveFilename (node:internal/modules/cjs/loader:941:27)
    at Function.resolve (node:internal/modules/cjs/helpers:109:19)
    at loadModuleData (/Users/timdp/Code/depcheck-test/node_modules/depcheck/dist/utils/index.js:48:26)
    at getCacheOrLoad (/Users/timdp/Code/depcheck-test/node_modules/depcheck/dist/special/bin.js:22:48)
    at getBinaries (/Users/timdp/Code/depcheck-test/node_modules/depcheck/dist/special/bin.js:31:23) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}
```

because Miniflare [uses](https://github.com/cloudflare/miniflare/blob/9265fa4d53262ce66278b91f2001b090e10696e8/packages/miniflare/package.json#L15-L18) ESM `exports` in package.json, which `require.resolve()` respects.

Theoretically, Miniflare could export package.json explicitly, but there's no need for that. I would recommend using [read-pkg](https://www.npmjs.com/package/read-pkg) instead of `require.resolve()` + `require()`.

### Versions

- `node -v`: v18.8.0
- `npm -v`: 8.18.0
- `depcheck --version`: 1.4.3

**Comment by dword-design** [comment]
I created a PR that fixes it https://github.com/depcheck/depcheck/pull/760.
