### ISSUE TITLE
typedoc doesn't find in npm scripts

### ISSUE THREAD

**Issue by regseb** [depcheck/depcheck#754]
### Bug Description

Depcheck indicates that the [`typedoc`](https://www.npmjs.com/package/typedoc) dependency is unused although it's in an npm script.

### Code snippets

```JSON
{
    "name": "testcase",
    "version": "1.0.0",
    "scripts": {
        "docs": "typedoc"
    },
    "dependencies": {
        "typedoc": "0.23.15"
    }
}
```

### Versions

- `node -v`: v18.9.1
- `npm -v`: 8.19.2
- `depcheck --version`: 1.4.3

### Extra info

```Shell
$ npm install

added 11 packages, and audited 12 packages in 4s

found 0 vulnerabilities
```

```Shell
$ npx depcheck --json
{"dependencies":["typedoc"],"devDependencies":[],"missing":{},"using":{},"invalidFiles":{},"invalidDirs":{}}
```

**Comment by regseb** [comment]
With `typedoc`, there is an error in the [`loadModuleData()`](https://github.com/depcheck/depcheck/blob/93eeaebd9fa8b43dcc5193bdf358be377bf0b2b3/src/utils/index.js) method:

```
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './package.json' is not defined by "exports" in /home/regseb/testcase/node_modules/typedoc/package.json
    at new NodeError (node:internal/errors:399:5)
    at exportsNotFound (node:internal/modules/esm/resolve:267:10)
    at packageExportsResolve (node:internal/modules/esm/resolve:603:9)
    at resolveExports (node:internal/modules/cjs/loader:569:36)
    at Module._findPath (node:internal/modules/cjs/loader:643:31)
    at Module._resolveFilename (node:internal/modules/cjs/loader:1068:27)
    at Function.resolve (node:internal/modules/helpers:127:19)
    at loadModuleData (/home/regseb/testcase/node_modules/depcheck/dist/utils/index.js:49:26)
    at getCacheOrLoad (/home/regseb/testcase/node_modules/depcheck/dist/special/bin.js:22:48)
    at getBinaries (/home/regseb/testcase/node_modules/depcheck/dist/special/bin.js:30:23) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}
```

I think the problem occurs with packages that don't export `package.json`. For example with [`typedoc` _0.23.15_](https://github.com/TypeStrong/typedoc/blob/v0.23.15/package.json#L7-L10):

```JSON
{
  "...": "...",
  "exports": {
    ".": "./dist/index.js",
    "./tsdoc.json": "./tsdoc.json"
  },
  "...": "..."
}
```

---

There's no longer any problem with `typedoc`, as the latest version exports [`package.json`](https://github.com/TypeStrong/typedoc/blob/v0.24.8/package.json#L6-L10).

And on the `main` branch of `depcheck`, the problem seems to have been corrected thanks to the https://github.com/depcheck/depcheck/commit/8951d580e147e1fdf0b4655b404347d8f119a510 commit:

> **add esm support for bin packages (https://github.com/depcheck/depcheck/pull/760)**
>
> The PR changes `loadModuleData` so that it supports ESM packages that do
not export `package.json`.
