### ISSUE TITLE
Next.js webpack configuration detection failed with the following error when using next-pwa

### ISSUE THREAD

**Issue by cjsewell** [depcheck/depcheck#763]
### Bug Description

When using Next JS with [next-pwa](https://www.npmjs.com/package/next-pwa) depcheck fails the webpack configuration detection with the following error:

```
Next.js webpack configuration detection failed with the following error TypeError: Cannot read properties of undefined (reading 'distDir')
    at Object.webpack (/project/node_modules/next-pwa/index.js:24:21)
    at loadNextWebpackConfig (/project/node_modules/depcheck/dist/special/webpack.js:157:25)
    at parseWebpack (/project/node_modules/depcheck/dist/special/webpack.js:187:27)
    at getDependencies (/project/node_modules/depcheck/dist/check.js:71:24)
    at /project/node_modules/depcheck/dist/check.js:97:32
    at Array.map (<anonymous>)
    at checkFile (/project/node_modules/depcheck/dist/check.js:97:18)
    at ReaddirpStream.<anonymous> (/project/node_modules/depcheck/dist/check.js:126:24)
    at ReaddirpStream.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:315:12) Support for this feature is new and experimental, please report issues at https://github.com/depcheck/depcheck/issues
```

Where the dependency is listed in package.json:

```
    "next": "13.0.6",
    "next-pwa": "5.6.0"
```

### Versions

- `node -v`: v16.17.1
- `npm -v`: 8.15.0
- `depcheck --version`: 1.4.3

### Extra info

- `next info`:
```
next info                                                                                                                                                                                      ─╯
    Operating System:
      Platform: linux
      Arch: x64
      Version: #27-Ubuntu SMP PREEMPT_DYNAMIC Wed Nov 23 20:44:15 UTC 2022
    Binaries:
      Node: 16.17.1
      npm: 8.15.0
      Yarn: 3.3.0
      pnpm: N/A
    Relevant packages:
      next: 13.0.6
      eslint-config-next: 13.0.6
      react: 18.2.0
      react-dom: 18.2.0
```

**Comment by cjsewell** [comment]
Related: https://github.com/depcheck/depcheck/issues/545#issuecomment-828644290
