### ISSUE TITLE
Parser doesn't appear to correctly load babel configuration

### ISSUE THREAD

**Issue by fnimick** [depcheck/depcheck#784]
### Bug Description

I'm received depcheck errors related to import assertions such as:
```
import type { ApolloError } from "@apollo/client/errors" assert { "resolution-mode": "import" };
```

Babel is configured as:
```
module.exports = {
  presets: [
    ["@babel/preset-env", { targets: { node: "current" } }],
    "@babel/preset-typescript",
  ],
  plugins: ["@babel/plugin-syntax-import-assertions"],
};
```

### Versions

- `node -v`: 18.14.1
- yarn: 3.4.1
- `depcheck --version`: 1.4.3

### Extra info

Any extra info you want to include. Thank you for the bug report!

BONUS POINTS: If you wish to help us debug further, the `depcheck --json` option will show more information. Check [here in the README](https://github.com/depcheck/depcheck#example) for documentation on json output.

```
{"dependencies":["@apollo/client","graphql","graphql-ws","next","next-with-apollo"],"devDependencies":["express","postgraphile"],"missing":{},"using":{"cross-env":["/Users/francis/millionmarker/starter/@app/lib/package.json"],"typescript":["/Users/francis/millionmarker/starter/@app/lib/package.json"],"react":["/Users/francis/millionmarker/starter/@app/lib/package.json","/Users/francis/millionmarker/starter/@app/lib/src/passwords.ts"],"rc-field-form":["/Users/francis/millionmarker/starter/@app/lib/src/passwords.ts"],"zxcvbn":["/Users/francis/millionmarker/starter/@app/lib/src/passwords.ts"],"@types/zxcvbn":["/Users/francis/millionmarker/starter/@app/lib/src/passwords.ts"],"react-dom":["/Users/francis/millionmarker/starter/@app/lib/src/passwords.ts"]},"invalidFiles":{"/Users/francis/millionmarker/starter/@app/lib/src/errors.ts":"SyntaxError: This experimental syntax requires enabling the parser plugin: 'importAssertions' (1:57)\n    at Parser._raise (/Users/francis/millionmarker/starter/node_modules/depcheck/node_modules/@babel/parser/lib/index.js:541:17)\n    at Parser.raiseWithData (/Users/francis/millionmarker/starter/node_modules/depcheck/node_modules/@babel/parser/lib/index.js:534:17)\n    at Parser.expectPlugin (/Users/francis/millionmarker/starter/node_modules/depcheck/node_modules/@babel/parser/lib/index.js:3585:18)\n    at Parser.maybeParseImportAssertions (/Users/francis/millionmarker/starter/node_modules/depcheck/node_modules/@babel/parser/lib/index.js:14929:12)\n    at Parser.parseImport (/Users/francis/millionmarker/starter/node_modules/depcheck/node_modules/@babel/parser/lib/index.js:14819:29)\n    at Parser.parseImport (/Users/francis/millionmarker/starter/node_modules/depcheck/node_modules/@babel/parser/lib/index.js:9449:30)\n    at Parser.parseStatementContent (/Users/francis/millionmarker/starter/node_modules/depcheck/node_modules/@babel/parser/lib/index.js:13454:27)\n    at Parser.parseStatementContent (/Users/francis/millionmarker/starter/node_modules/depcheck/node_modules/@babel/parser/lib/index.js:9528:18)\n    at Parser.parseStatement (/Users/francis/millionmarker/starter/node_modules/depcheck/node_modules/@babel/parser/lib/index.js:13352:17)\n    at Parser.parseBlockOrModuleBlockBody (/Users/francis/millionmarker/starter/node_modules/depcheck/node_modules/@babel/parser/lib/index.js:13941:25)"},"invalidDirs":{}}
```

**Comment by znarf** [comment]
Should have been fixed in https://github.com/depcheck/depcheck/pull/823
