### ISSUE TITLE
ReferenceError: Promise is not defined

### ISSUE THREAD

**Issue by cblair** [depcheck/depcheck#84]
Using node v0.10.38. All I did was npm install -g depcheck and try to run it. I need to remember where Promise comes from, but seems like depcheck's package.json dependencies is incomplete.

```
>>$ depcheck 

/home/colbblai/.nvm/v0.10.38/lib/node_modules/depcheck/dist/cli.js:39
  return new Promise(function (resolve, reject) {
             ^
ReferenceError: Promise is not defined
    at checkPathExist (/home/colbblai/.nvm/v0.10.38/lib/node_modules/depcheck/dist/cli.js:39:14)
    at /home/colbblai/.nvm/v0.10.38/lib/node_modules/depcheck/dist/cli.js:87:7
    at cli (/home/colbblai/.nvm/v0.10.38/lib/node_modules/depcheck/dist/cli.js:113:7)
    at Object.<anonymous> (/home/colbblai/.nvm/v0.10.38/lib/node_modules/depcheck/bin/depcheck:5:23)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
```

**Comment by lijunle** [comment]
Sorry, we don't support v0.10.x anymore. Please upgrade to 0.12.x or newer. I could like to update the `package.json` file.

**Comment by lijunle** [comment]
I have specified the version in package.json file.

**Comment by cblair** [comment]
Seems like a good fix, I'll try again.
