### ISSUE TITLE
NVD Update Fails at 82% repeatedly for the last 12+ hours 

### ISSUE THREAD

**Issue by rupreck** [depcheck/depcheck#896]
The NVD update reaches 82% then stops.  This has occurred with multiple different servers for the last 12+ hours.

This has blocked our pipeline for that time.  Is there a workaround?  e.g. a web address we can manually download the update data and extract it to our cache?

Error:

```
org.owasp.dependencycheck.data.update.exception.UpdateException: Error updating the NVD Data
        at org.owasp.dependencycheck.data.update.NvdApiDataSource.processApi(NvdApiDataSource.java:389)
        at org.owasp.dependencycheck.data.update.NvdApiDataSource.update(NvdApiDataSource.java:116)
        at org.owasp.dependencycheck.Engine.doUpdates(Engine.java:906)
        at org.owasp.dependencycheck.Engine.doUpdates(Engine.java:878)
        at org.owasp.dependencycheck.App.runUpdateOnly(App.java:427)
        at org.owasp.dependencycheck.App.run(App.java:172)
        at org.owasp.dependencycheck.App.main(App.java:89)
Caused by: io.github.jeremylong.openvulnerability.client.nvd.NvdApiRetryExceededException: NVD Update Failed: attempted to retrieve starting index 224000 from the NVD unsuccessfully five times.

```

We use an nvdApiKey.

**Comment by rumpl** [comment]
What is NVD? 

I see some java stacktraces, how is this related to depcheck?

**Comment by rupreck** [comment]
The commands our script runs are as follows...

set JAVA_HOME=S:\sqa\node\tools\java\jdk17
set path=%PATH%;S:\sqa\node\tools\java\jdk17\bin
S:\sqa\node\tools\dependency-check\bin\dependency-check --nvdApiKey 01495f0c-23da-4f77-9bc2-f06e595eddc9 --updateonly --data S:\sqa\depcheckdata

**Comment by rupreck** [comment]
sorry... wrong project
