### ISSUE TITLE
ES6 import pkg from '../package.json' with {type: 'json'} - fails the parser

### ISSUE THREAD

**Issue by hands-on-masters** [depcheck/depcheck#908]
### Bug Description

parser fails on the below line
import pkg from '../package.json' with {type: 'json'}

SyntaxError: This experimental syntax requires enabling the parser plugin: \"importAttributes\". (1:39)\n    at constructor (monorepo/node_modules/.pnpm/@babel+parser@7.25.3/node_modules/@babel/parser/lib/index.js:349:19)\n    at FlowParserMixin.raise (modules/.pnpm/@babel+parser@7.25.3/node_modules/@babel/parser/lib/index.js:3247:19)\n    at FlowParserMixin.expectPlugin (node_modules/.pnpm/@babel+parser@7.25.3/node_modules/@babel/parser/lib/index.js:3275:16)\n    at FlowParserMixin.expectImportAttributesPlugin (monorepo/node_modules/.pnpm/@babel+parser@7.25.3/node_modules/@babel/parser/lib/index.js:10701:12)\n    at FlowParserMixin.maybeParseImportAttributes (monorepo/node_modules/.pnpm/@babel+parser@7.25.3/node_modules/@babel/parser/lib/index.js:13780:16)\n    at FlowParserMixin.parseImportSourceAndAttributes (monorepo/node_modules/.pnpm/@babel+parser@7.25.3/node_modules/@babel/parser/lib/index.js:13693:10)\n    at FlowParserMixin.parseImportSpecifiersAndAfter (monorepo/node_modules/.pnpm/@babel+parser@7.25.3/node_modules/@babel/parser/lib/index.js:13687:17)\n    at FlowParserMixin.parseImport (/modules/.pnpm/@babel+parser@7.25.3/node_modules/@babel/parser/lib/index.js:13678:17)\n    at FlowParserMixin.parseStatementContent (monorepo/node_modules/.pnpm/@babel+parser@7.25.3/node_modules/@babel/parser/lib/index.js:12325:27)\n    at FlowParserMixin.parseStatementLike (monorepo/node_modules/.pnpm/@babel+parser@7.25.3/node_modules/@babel/parser/lib/index.js:12217:17)

A description of the bug

### Code snippets
```
import pkg from '../package.json' with {type: 'json'}
```

Where the dependency is used:

import pkg from '../package.json' with {type: 'json'}
import { setupAppRouter } from './routes/index.js'
import { start } from '@dev-devsuccess/fintech-express'
import { getAppLogger } from '@dev-devsuccess/fintech-logger'

Where the dependency is listed in package.json:

```
 "type": "module",
"dependencies": {
        "@dev-devsuccess/fintech-express": "workspace:*",
        "@dev-devsuccess/fintech-test": "workspace:*",
        "lodash-es": "4.17.21",
        "prom-client": "15.1.1"
    },
 "devDependencies": {
        "@dev-devsuccess/fintech-eslint": "workspace:*",
        "cross-env": "7.0.3"
    },
```

### Versions

- `node -v`: 22.5.1
- `npm -v`: 10.8.2
- `depcheck --version`: 1.4.7

### Extra info

Any extra info you want to include. Thank you for the bug report!

{"dependencies":["@dev-devsuccess/fintech-express","@dev-devsuccess/fintech-test"],"devDependencies":[],"missing":{},"using":{"@dev-devsuccess/fintech-eslint":["monorepo/services/test/fintech-test-svc/package.json"],"cross-env":["monorepo/services/test/fintech-test-svc/package.json"],"@dev-devsuccess/fintech-config-core":["monorepo/services/test/fintech-test-svc/lib/index.js"],"@dev-devsuccess/fintech-logger":["monorepo/services/test/fintech-test-svc/lib/index.js","monorepo/services/test/fintech-test-svc/lib/graphql/resolvers/testData.js"],"prom-client":["monorepo/services/test/fintech-test-svc/lib/metrics.js"],"@dev-devsuccess/fintech-graphql":["monorepo/services/test/fintech-test-svc/lib/routes/index.js","monorepo/services/test/fintech-test-svc/lib/graphql/schema/index.js","monorepo/services/test/fintech-test-svc/lib/graphql/schema/testData.js"],"lodash-es":["monorepo/services/test/fintech-test-svc/lib/graphql/resolvers/testData.js"]},"invalidFiles":{"monorepo/services/test/fintech-test-svc/lib/server.js":"SyntaxError: This experimental syntax requires enabling the parser plugin: \"importAttributes\". (1:39)\n    at constructor (monorepo/node_modules/.pnpm/@babel+parser@7.25.3/node_modules/@babel/parser/lib/index.js:349:19)\n    at FlowParserMixin.raise (monorepo/node_modules/.pnpm/@babel+parser@7.25.3/node_modules/@babel/parser/lib/index.js:3247:19)\n    at FlowParserMixin.expectPlugin (monorepo/node_modules/.pnpm/@babel+parser@7.25.3/node_modules/@babel/parser/lib/index.js:3275:16)\n    at FlowParserMixin.expectImportAttributesPlugin (monorepo/node_modules/.pnpm/@babel+parser@7.25.3/node_modules/@babel/parser/lib/index.js:10701:12)\n    at FlowParserMixin.maybeParseImportAttributes (monorepo/node_modules/.pnpm/@babel+parser@7.25.3/node_modules/@babel/parser/lib/index.js:13780:16)\n    at FlowParserMixin.parseImportSourceAndAttributes (monorepo/node_modules/.pnpm/@babel+parser@7.25.3/node_modules/@babel/parser/lib/index.js:13693:10)\n    at FlowParserMixin.parseImportSpecifiersAndAfter (monorepo/node_modules/.pnpm/@babel+parser@7.25.3/node_modules/@babel/parser/lib/index.js:13687:17)\n    at FlowParserMixin.parseImport (monorepo/node_modules/.pnpm/@babel+parser@7.25.3/node_modules/@babel/parser/lib/index.js:13678:17)\n    at FlowParserMixin.parseStatementContent (monorepo/node_modules/.pnpm/@babel+parser@7.25.3/node_modules/@babel/parser/lib/index.js:12325:27)\n    at FlowParserMixin.parseStatementLike (monorepo/node_modules/.pnpm/@babel+parser@7.25.3/node_modules/@babel/parser/lib/index.js:12217:17)"},"invalidDirs":{}}

**Comment by hands-on-masters** [comment]
i had replaced the above code with
import { readFile } from 'fs/promises'
const pkg = JSON.parse(await readFile(new URL('../package.json', import.meta.url)))

Closing for now as the workaround is acceptable
